#!/usr/bin/env python3
"""Generate a standalone Teensy-idiom imxrt1176.h from the NXP CMSIS header.

Emits `#define <PREFIX>_<REG> (*(volatile uint32_t *)0x...)` for the peripherals
Phase 0 needs.  Reads peripheral base addresses from the NXP MIMXRT1176_cm7_COMMON.h
`#define <INST>_BASE (...)` lines.  Output has no SDK dependency.

NOTE: Base addresses are in MIMXRT1176_cm7_COMMON.h (not the top-level
MIMXRT1176_cm7.h which only has peripheral-struct #includes).
"""
import re, sys, pathlib

SDK = pathlib.Path.home() / "Development/nxp/mcux-devices-rt/RT1170/MIMXRT1176/MIMXRT1176_cm7_COMMON.h"
OUT = pathlib.Path(__file__).resolve().parent.parent / "imxrt1176.h"

WANTED = {"CCM": "CCM", "IOMUXC": "IOMUXC", "IOMUXC_GPR": "IOMUXC_GPR",
          "FLEXSPI1": "FLEXSPI", "FLEXSPI2": "FLEXSPI2",
          "ANADIG_PLL": "ANADIG_PLL", "ANADIG_OSC": "ANADIG_OSC",
          **{f"GPIO{i}": f"GPIO{i}" for i in range(1, 14)}}

# --- CCM clock roots (Task 9: 996 MHz core clock tree) -----------------------
# CCM->CLOCK_ROOT[n].CONTROL is at CCM_BASE + n*0x80 (CONTROL at struct offset 0).
# We emit the roots the 996 MHz bring-up touches.  See SDK BOARD_BootClockRUN /
# clock_root_t enum (fsl_clock.h):  M7=0, Bus=2, M7_Systick=8.
CCM_ROOT_STRIDE = 0x80
CCM_CLOCK_ROOTS = {0: "M7", 2: "BUS", 8: "M7_SYSTICK"}

# ANADIG_PLL / ANADIG_OSC register offsets (from MIMXRT1176_cm7.h peripheral
# struct layouts).  Both blocks share base 0x40C84000 in the analog top.
ANADIG_PLL_REGS = {"ARM_PLL_CTRL": 0x200}   # ARM_PLL_CTRL_REGISTER, offset 0x200
ANADIG_OSC_REGS = {"OSC_24M_CTRL": 0x020}   # 24MHz OSC Control,      offset 0x020

# --- IOMUXC per-pad mux / pad-control registers (Task 11: EVKB pin table) -----
# Offsets from IOMUXC_BASE (0x400E8000), derived from the SDK's pin-mux macros
# in fsl_iomuxc.h.  Each macro `IOMUXC_<PAD>_<SIGNAL>` expands to
#   muxRegister, muxMode, inputRegister, inputDaisy, configRegister
# e.g. IOMUXC_GPIO_AD_04_GPIO9_IO03 = 0x400E811C, 0xA, 0, 0, 0x400E8360
# so SW_MUX_CTL_PAD_GPIO_AD_04 @ +0x11C, SW_PAD_CTL_PAD_GPIO_AD_04 @ +0x360.
# muxMode 0xA (ALT10) selects GPIO9_IO03 (the EVKB User LED D6, GPIO9 bit 3).
IOMUXC_MUX_CTL_REGS = {"GPIO_AD_04": 0x11C}
IOMUXC_PAD_CTL_REGS = {"GPIO_AD_04": 0x360}
# LPUART1 console pins (EVKB VCOM): TX=GPIO_AD_24, RX=GPIO_AD_25.
IOMUXC_MUX_CTL_REGS.update({"GPIO_AD_24": 0x16C, "GPIO_AD_25": 0x170})
IOMUXC_PAD_CTL_REGS.update({"GPIO_AD_24": 0x3B0, "GPIO_AD_25": 0x3B4})
# LPADC1 analog input A0 = GPIO_AD_06 (ADC1_CH0A). Muxed to a non-driving ALT so
# the ADC can tap the pad (per the SDK lpadc example: ALT5 GPIO_MUX3_IO05).
IOMUXC_MUX_CTL_REGS.update({"GPIO_AD_06": 0x124})
IOMUXC_PAD_CTL_REGS.update({"GPIO_AD_06": 0x368})

def parse_bases(txt):
    bases = {}
    for m in re.finditer(r'#define\s+(\w+)_BASE\s+\(([0-9a-fA-Fxu]+)\)', txt):
        try: bases[m.group(1)] = int(m.group(2).rstrip("uU"), 0)
        except ValueError: pass
    return bases

def main():
    bases = parse_bases(SDK.read_text())
    L = ["/* AUTO-GENERATED by tools/gen_imxrt1176_h.py -- do not edit by hand.",
         " * Standalone Teensy-idiom register defs for NXP i.MX RT1176 (CM7). */",
         "#ifndef _imxrt1176_h_", "#define _imxrt1176_h_", "#include <stdint.h>", ""]
    for inst, pfx in sorted(WANTED.items()):
        b = bases.get(inst)
        if b is None: print(f"warn: no base for {inst}", file=sys.stderr); continue
        L.append(f"#define {pfx}_BASE 0x{b:08X}u")
    for i in range(1, 14):
        b = bases.get(f"GPIO{i}")
        if b is None: continue
        L += [f"#define GPIO{i}_DR        (*(volatile uint32_t *)0x{b+0x00:08X}u)",
              f"#define GPIO{i}_GDIR      (*(volatile uint32_t *)0x{b+0x04:08X}u)",
              f"#define GPIO{i}_PSR       (*(volatile uint32_t *)0x{b+0x08:08X}u)",
              f"#define GPIO{i}_DR_SET    (*(volatile uint32_t *)0x{b+0x84:08X}u)",
              f"#define GPIO{i}_DR_CLEAR  (*(volatile uint32_t *)0x{b+0x88:08X}u)",
              f"#define GPIO{i}_DR_TOGGLE (*(volatile uint32_t *)0x{b+0x8C:08X}u)"]
    # --- CCM clock-root CONTROL registers (Task 9) ---------------------------
    ccm = bases.get("CCM")
    if ccm is not None:
        L.append("")
        L.append("/* CCM clock roots: CCM->CLOCK_ROOT[n].CONTROL @ CCM_BASE + n*0x80 */")
        for n, nm in sorted(CCM_CLOCK_ROOTS.items()):
            addr = ccm + n * CCM_ROOT_STRIDE
            L.append(f"#define CCM_CLOCK_ROOT{n}_CONTROL (*(volatile uint32_t *)0x{addr:08X}u) /* {nm} */")
        L += ["#define CCM_CLOCK_ROOT_CONTROL_MUX(x)  (((uint32_t)(x) << 8) & 0x700u)",
              "#define CCM_CLOCK_ROOT_CONTROL_DIV(x)  (((uint32_t)(x) << 0) & 0x0FFu)"]

    # --- ANADIG PLL / OSC registers (Task 9: ARM PLL = 996 MHz, 24M OSC) ------
    apll = bases.get("ANADIG_PLL")
    if apll is not None:
        L.append("")
        for nm, off in sorted(ANADIG_PLL_REGS.items()):
            L.append(f"#define ANADIG_PLL_{nm} (*(volatile uint32_t *)0x{apll+off:08X}u)")
        L += ["#define ANADIG_PLL_ARM_PLL_CTRL_DIV_SELECT(x)   (((uint32_t)(x) << 0) & 0x000000FFu)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_HOLD_RING_OFF   (1u << 12)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_POWERUP         (1u << 13)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ENABLE_CLK      (1u << 14)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_POST_DIV_SEL(x) (((uint32_t)(x) << 15) & 0x00018000u)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_BYPASS          (1u << 17)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_STABLE  (1u << 29)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_GATE    (1u << 30)"]
    aosc = bases.get("ANADIG_OSC")
    if aosc is not None:
        for nm, off in sorted(ANADIG_OSC_REGS.items()):
            L.append(f"#define ANADIG_OSC_{nm} (*(volatile uint32_t *)0x{aosc+off:08X}u)")
        L += ["#define ANADIG_OSC_OSC_24M_CTRL_OSC_EN          (1u << 4)",
              "#define ANADIG_OSC_OSC_24M_CTRL_LP_EN           (1u << 2)",
              "#define ANADIG_OSC_OSC_24M_CTRL_OSC_24M_STABLE  (1u << 30)"]

    # --- IOMUXC per-pad mux / pad-ctl registers (Task 11) --------------------
    iomuxc = bases.get("IOMUXC")
    if iomuxc is not None and (IOMUXC_MUX_CTL_REGS or IOMUXC_PAD_CTL_REGS):
        L.append("")
        L.append("/* IOMUXC per-pad mux/pad-control regs (offsets from fsl_iomuxc.h) */")
        for pad, off in sorted(IOMUXC_MUX_CTL_REGS.items()):
            L.append(f"#define IOMUXC_SW_MUX_CTL_PAD_{pad} (*(volatile uint32_t *)0x{iomuxc+off:08X}u)")
        for pad, off in sorted(IOMUXC_PAD_CTL_REGS.items()):
            L.append(f"#define IOMUXC_SW_PAD_CTL_PAD_{pad} (*(volatile uint32_t *)0x{iomuxc+off:08X}u)")

    L += ["", "#define SYST_CSR   (*(volatile uint32_t *)0xE000E010u)",
          "#define SYST_RVR   (*(volatile uint32_t *)0xE000E014u)",
          "#define SYST_CVR   (*(volatile uint32_t *)0xE000E018u)",
          "#define SCB_VTOR   (*(volatile uint32_t *)0xE000ED08u)",
          "#define SCB_ICSR   (*(volatile uint32_t *)0xE000ED04u)",
          "#define SCB_ICSR_PENDSTSET (1u << 26)",
          "#define ARM_DWT_CYCCNT (*(volatile uint32_t *)0xE0001004u)",
          "#define ARM_DWT_CTRL   (*(volatile uint32_t *)0xE0001000u)",
          "#define ARM_DEMCR      (*(volatile uint32_t *)0xE000EDFCu)",
          "#define ARM_DEMCR_TRCENA (1u << 24)"]
    L += ["",
          "/* --- Cortex-M7 NVIC (Task: interrupt infrastructure) --- */",
          "#define NVIC_ISER(n) (*(volatile uint32_t *)(0xE000E100u + ((n) << 2)))",
          "#define NVIC_ICER(n) (*(volatile uint32_t *)(0xE000E180u + ((n) << 2)))",
          "#define NVIC_ISPR(n) (*(volatile uint32_t *)(0xE000E200u + ((n) << 2)))",
          "#define NVIC_ICPR(n) (*(volatile uint32_t *)(0xE000E280u + ((n) << 2)))",
          "#define NVIC_IP(n)   (*(volatile uint8_t  *)(0xE000E400u + (n)))",
          "#define NVIC_ENABLE_IRQ(n)   (NVIC_ISER((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_DISABLE_IRQ(n)  (NVIC_ICER((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_SET_PENDING(n)  (NVIC_ISPR((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_CLEAR_PENDING(n)(NVIC_ICPR((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_SET_PRIORITY(n, p) (NVIC_IP(n) = (uint8_t)(p))"]
    # --- LPUART register blocks + bitfields (Task: Serial1) -----------------
    LPUART_BASES = {1:0x4007C000, 2:0x40080000, 3:0x40084000, 4:0x40088000,
                    5:0x4008C000, 6:0x40090000, 7:0x40094000, 8:0x40098000,
                    9:0x4009C000, 10:0x400A0000, 11:0x40C24000, 12:0x40C28000}
    LPUART_REGS = {"VERID":0x0,"PARAM":0x4,"GLOBAL":0x8,"PINCFG":0xC,"BAUD":0x10,
                   "STAT":0x14,"CTRL":0x18,"DATA":0x1C,"MATCH":0x20,"MODIR":0x24,
                   "FIFO":0x28,"WATER":0x2C}
    L += ["", "/* --- LPUART register blocks (Task: Serial1) --- */"]
    for n, base in sorted(LPUART_BASES.items()):
        for reg, off in LPUART_REGS.items():
            L.append(f"#define LPUART{n}_{reg} (*(volatile uint32_t *)0x{base+off:08X}u)")
    L += ["",
          "/* LPUART bitfields (RT1176 RM / PERI_LPUART.h) */",
          "#define LPUART_STAT_RDRF   (1u << 21)",
          "#define LPUART_STAT_TDRE   (1u << 23)",
          "#define LPUART_STAT_TC     (1u << 22)",
          "#define LPUART_STAT_IDLE   (1u << 20)",
          "#define LPUART_STAT_OR     (1u << 19)",
          "#define LPUART_CTRL_RE     (1u << 18)",
          "#define LPUART_CTRL_TE     (1u << 19)",
          "#define LPUART_CTRL_ILIE   (1u << 20)",
          "#define LPUART_CTRL_RIE    (1u << 21)",
          "#define LPUART_CTRL_TCIE   (1u << 22)",
          "#define LPUART_CTRL_TIE    (1u << 23)",
          "#define LPUART_BAUD_SBR(n)   ((uint32_t)(n) & 0x1FFFu)",
          "#define LPUART_BAUD_OSR(n)   (((uint32_t)(n) & 0x1Fu) << 24)",
          "#define LPUART_BAUD_BOTHEDGE (1u << 17)",
          "#define LPUART_FIFO_RXFE   (1u << 3)",
          "#define LPUART_FIFO_TXFE   (1u << 7)",
          "#define LPUART_WATER_TXWATER(n) ((uint32_t)(n) & 0x3u)",
          "#define LPUART_WATER_RXWATER(n) (((uint32_t)(n) << 16) & 0x30000u)"]
    L += ["",
          "/* LPUART1 console clock + input select (EVKB VCOM) */",
          "#define CCM_CLOCK_ROOT25_CONTROL (*(volatile uint32_t *)0x40CC0C80u)",
          "#define CCM_LPCG86_DIRECT        (*(volatile uint32_t *)0x40CC6AC0u)",
          "#define IOMUXC_LPUART1_TXD_SELECT_INPUT (*(volatile uint32_t *)0x400E8620u)",
          "#define IOMUXC_LPUART1_RXD_SELECT_INPUT (*(volatile uint32_t *)0x400E861Cu)"]
    # --- LPADC (ADC1/ADC2) register blocks + bitfields (Task: analogRead) ---
    ADC_BASES = {1: 0x40050000, 2: 0x40054000}
    ADC_REGS = {"VERID":0x0,"PARAM":0x4,"CTRL":0x10,"STAT":0x14,"IE":0x18,"DE":0x1C,
                "CFG":0x20,"PAUSE":0x24,"FCTRL":0x30,"SWTRIG":0x34,
                "TCTRL0":0xC0,"CMDL1":0x100,"CMDH1":0x104,"RESFIFO":0x300}
    L += ["", "/* --- LPADC register blocks (Task: analogRead) --- */"]
    for n, base in sorted(ADC_BASES.items()):
        for reg, off in ADC_REGS.items():
            L.append(f"#define ADC{n}_{reg} (*(volatile uint32_t *)0x{base+off:08X}u)")
    L += ["",
          "/* LPADC bitfields (RT1176 RM / PERI_ADC.h) */",
          "#define ADC_CTRL_ADCEN   (1u << 0)",
          "#define ADC_CTRL_RST     (1u << 1)",
          "#define ADC_CTRL_RSTFIFO (1u << 8)",
          "#define ADC_STAT_RDY     (1u << 0)",
          "#define ADC_STAT_FOF     (1u << 1)",
          "#define ADC_IE_FWMIE     (1u << 0)",
          "#define ADC_CMDL_ADCH(x)   ((uint32_t)(x) & 0x1Fu)",
          "#define ADC_TCTRL_TCMD(x)  (((uint32_t)(x) & 0xFu) << 24)",
          "#define ADC_FCTRL_FWMARK(x)(((uint32_t)(x) & 0xFu) << 16)",
          "#define ADC_CFG_PWRSEL(x)  (((uint32_t)(x) & 0x3u) << 4)",
          "#define ADC_CFG_REFSEL(x)  (((uint32_t)(x) & 0x3u) << 6)",
          "#define ADC_RESFIFO_D      (0xFFFFu)",
          "#define ADC_RESFIFO_VALID  (1u << 31)",
          "",
          "/* LPADC clock roots + LPCG gates */",
          "#define CCM_CLOCK_ROOT9_CONTROL  (*(volatile uint32_t *)0x40CC0480u)",
          "#define CCM_CLOCK_ROOT10_CONTROL (*(volatile uint32_t *)0x40CC0500u)",
          "#define CCM_LPCG55_DIRECT (*(volatile uint32_t *)0x40CC66E0u)",
          "#define CCM_LPCG56_DIRECT (*(volatile uint32_t *)0x40CC6700u)"]
    L += ["",
          "/* IOMUXC_GPR FlexRAM bank-config registers (base 0x400E4000) */",
          "#define IOMUXC_GPR_GPR14 (*(volatile uint32_t *)0x400E4038u)",
          "#define IOMUXC_GPR_GPR16 (*(volatile uint32_t *)0x400E4040u)",
          "#define IOMUXC_GPR_GPR17 (*(volatile uint32_t *)0x400E4044u)  /* FLEXRAM_BANK_CFG_LOW  (banks 0-7)  */",
          "#define IOMUXC_GPR_GPR18 (*(volatile uint32_t *)0x400E4048u)  /* FLEXRAM_BANK_CFG_HIGH (banks 8-15) */"]
    L += ["",
          "/* SRC (System Reset Controller, base 0x40C04000) - dual-core reset control.",
          " * SRSR bitmap (nxp PERI_SRC.h): bit2 M7_LOCKUP, bit12 M4_LOCKUP_M7, bit0/16 POR. */",
          "#define SRC_SRMR (*(volatile uint32_t *)0x40C04004u)  /* [7:6] M4LOCKUP_RESET_MODE, [11:10] M4REQ_RESET_MODE */",
          "#define SRC_SRSR (*(volatile uint32_t *)0x40C04010u)  /* reset status (write 1 to clear) */"]
    L += ["",
          "/* LPI2C1 (Arduino-header I2C master), base 0x40104000 */",
          "#define LPI2C1_MCR    (*(volatile uint32_t *)0x40104010u)",
          "#define LPI2C1_MSR    (*(volatile uint32_t *)0x40104014u)",
          "#define LPI2C1_MIER   (*(volatile uint32_t *)0x40104018u)",
          "#define LPI2C1_MCFGR1 (*(volatile uint32_t *)0x40104024u)",
          "#define LPI2C1_MCCR0  (*(volatile uint32_t *)0x40104048u)",
          "#define LPI2C1_MFCR   (*(volatile uint32_t *)0x40104058u)",
          "#define LPI2C1_MTDR   (*(volatile uint32_t *)0x40104060u)",
          "#define LPI2C1_MRDR   (*(volatile uint32_t *)0x40104070u)",
          "/* LPI2C1 clock: CCM_CLOCK_ROOT37 + LPCG98 */",
          "#define CCM_CLOCK_ROOT37_CONTROL (*(volatile uint32_t *)0x40CC1280u)",
          "#define CCM_LPCG98_DIRECT        (*(volatile uint32_t *)0x40CC6C40u)",
          "/* LPI2C1 pins: SCL=GPIO_AD_08, SDA=GPIO_AD_09 (ALT1) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_08 (*(volatile uint32_t *)0x400E812Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_09 (*(volatile uint32_t *)0x400E8130u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_08 (*(volatile uint32_t *)0x400E8370u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_09 (*(volatile uint32_t *)0x400E8374u)",
          "#define IOMUXC_LPI2C1_SCL_SELECT_INPUT   (*(volatile uint32_t *)0x400E85ACu)",
          "#define IOMUXC_LPI2C1_SDA_SELECT_INPUT   (*(volatile uint32_t *)0x400E85B0u)"]
    L += ["",
          "/* LPI2C1 slave register block */",
          "#define LPI2C1_SCR    (*(volatile uint32_t *)0x40104110u)",
          "#define LPI2C1_SSR    (*(volatile uint32_t *)0x40104114u)",
          "#define LPI2C1_SIER   (*(volatile uint32_t *)0x40104118u)",
          "#define LPI2C1_SCFGR1 (*(volatile uint32_t *)0x40104124u)",
          "#define LPI2C1_SCFGR2 (*(volatile uint32_t *)0x40104128u)",
          "#define LPI2C1_SAMR   (*(volatile uint32_t *)0x40104140u)",
          "#define LPI2C1_SASR   (*(volatile uint32_t *)0x40104150u)",
          "#define LPI2C1_STAR   (*(volatile uint32_t *)0x40104154u)",
          "#define LPI2C1_STDR   (*(volatile uint32_t *)0x40104160u)",
          "#define LPI2C1_SRDR   (*(volatile uint32_t *)0x40104170u)",
          "/* LPI2C2 (QEMU loopback slave), base 0x40108000 */",
          "#define LPI2C2_MCR    (*(volatile uint32_t *)0x40108010u)",
          "#define LPI2C2_MSR    (*(volatile uint32_t *)0x40108014u)",
          "#define LPI2C2_MIER   (*(volatile uint32_t *)0x40108018u)",
          "#define LPI2C2_MCFGR1 (*(volatile uint32_t *)0x40108024u)",
          "#define LPI2C2_MCCR0  (*(volatile uint32_t *)0x40108048u)",
          "#define LPI2C2_MTDR   (*(volatile uint32_t *)0x40108060u)",
          "#define LPI2C2_MRDR   (*(volatile uint32_t *)0x40108070u)",
          "#define LPI2C2_SCR    (*(volatile uint32_t *)0x40108110u)",
          "#define LPI2C2_SSR    (*(volatile uint32_t *)0x40108114u)",
          "#define LPI2C2_SIER   (*(volatile uint32_t *)0x40108118u)",
          "#define LPI2C2_SCFGR1 (*(volatile uint32_t *)0x40108124u)",
          "#define LPI2C2_SCFGR2 (*(volatile uint32_t *)0x40108128u)",
          "#define LPI2C2_SAMR   (*(volatile uint32_t *)0x40108140u)",
          "#define LPI2C2_SASR   (*(volatile uint32_t *)0x40108150u)",
          "#define LPI2C2_STAR   (*(volatile uint32_t *)0x40108154u)",
          "#define LPI2C2_STDR   (*(volatile uint32_t *)0x40108160u)",
          "#define LPI2C2_SRDR   (*(volatile uint32_t *)0x40108170u)",
          "/* LPI2C2 clock: CCM_CLOCK_ROOT38 + LPCG99 */",
          "#define CCM_CLOCK_ROOT38_CONTROL (*(volatile uint32_t *)0x40CC1300u)",
          "#define CCM_LPCG99_DIRECT        (*(volatile uint32_t *)0x40CC6C60u)"]
    L += ["", "#endif"]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")

if __name__ == "__main__": main()
