#!/usr/bin/env python3
"""Generate a standalone Teensy-idiom imxrt1176.h from the NXP CMSIS header.

Emits `#define <PREFIX>_<REG> (*(volatile uint32_t *)0x...)` for the peripherals
Phase 0 needs.  Reads peripheral base addresses from the NXP MIMXRT1176_cm7_COMMON.h
`#define <INST>_BASE (...)` lines.  Output has no SDK dependency.

NOTE: Base addresses are in MIMXRT1176_cm7_COMMON.h (not the top-level
MIMXRT1176_cm7.h which only has peripheral-struct #includes).
"""
import re, sys, pathlib

SDK = pathlib.Path.home() / "Development/nxp/mcux-devices-rt/RT1170/MIMXRT1176/MIMXRT1176_cm7_COMMON.h"
OUT = pathlib.Path(__file__).resolve().parent.parent / "imxrt1176.h"

WANTED = {"CCM": "CCM", "IOMUXC": "IOMUXC", "IOMUXC_GPR": "IOMUXC_GPR",
          "FLEXSPI1": "FLEXSPI", "FLEXSPI2": "FLEXSPI2",
          **{f"GPIO{i}": f"GPIO{i}" for i in range(1, 14)}}

def parse_bases(txt):
    bases = {}
    for m in re.finditer(r'#define\s+(\w+)_BASE\s+\(([0-9a-fA-Fxu]+)\)', txt):
        try: bases[m.group(1)] = int(m.group(2).rstrip("uU"), 0)
        except ValueError: pass
    return bases

def main():
    bases = parse_bases(SDK.read_text())
    L = ["/* AUTO-GENERATED by tools/gen_imxrt1176_h.py -- do not edit by hand.",
         " * Standalone Teensy-idiom register defs for NXP i.MX RT1176 (CM7). */",
         "#ifndef _imxrt1176_h_", "#define _imxrt1176_h_", "#include <stdint.h>", ""]
    for inst, pfx in sorted(WANTED.items()):
        b = bases.get(inst)
        if b is None: print(f"warn: no base for {inst}", file=sys.stderr); continue
        L.append(f"#define {pfx}_BASE 0x{b:08X}u")
    for i in range(1, 14):
        b = bases.get(f"GPIO{i}")
        if b is None: continue
        L += [f"#define GPIO{i}_DR        (*(volatile uint32_t *)0x{b+0x00:08X}u)",
              f"#define GPIO{i}_GDIR      (*(volatile uint32_t *)0x{b+0x04:08X}u)",
              f"#define GPIO{i}_PSR       (*(volatile uint32_t *)0x{b+0x08:08X}u)",
              f"#define GPIO{i}_DR_SET    (*(volatile uint32_t *)0x{b+0x84:08X}u)",
              f"#define GPIO{i}_DR_CLEAR  (*(volatile uint32_t *)0x{b+0x88:08X}u)",
              f"#define GPIO{i}_DR_TOGGLE (*(volatile uint32_t *)0x{b+0x8C:08X}u)"]
    L += ["#define SYST_CSR   (*(volatile uint32_t *)0xE000E010u)",
          "#define SYST_RVR   (*(volatile uint32_t *)0xE000E014u)",
          "#define SYST_CVR   (*(volatile uint32_t *)0xE000E018u)",
          "#define SCB_VTOR   (*(volatile uint32_t *)0xE000ED08u)",
          "#define ARM_DWT_CYCCNT (*(volatile uint32_t *)0xE0001004u)",
          "#define ARM_DWT_CTRL   (*(volatile uint32_t *)0xE0001000u)",
          "#define ARM_DEMCR      (*(volatile uint32_t *)0xE000EDFCu)",
          "#define ARM_DEMCR_TRCENA (1u << 24)", "", "#endif"]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")

if __name__ == "__main__": main()
