#!/usr/bin/env python3
"""Generate a standalone Teensy-idiom imxrt1176.h from the NXP CMSIS header.

Emits `#define <PREFIX>_<REG> (*(volatile uint32_t *)0x...)` for the peripherals
Phase 0 needs.  Reads peripheral base addresses from the NXP MIMXRT1176_cm7_COMMON.h
`#define <INST>_BASE (...)` lines.  Output has no SDK dependency.

NOTE: Base addresses are in MIMXRT1176_cm7_COMMON.h (not the top-level
MIMXRT1176_cm7.h which only has peripheral-struct #includes).
"""
import re, sys, pathlib

SDK = pathlib.Path.home() / "Development/nxp/mcux-devices-rt/RT1170/MIMXRT1176/MIMXRT1176_cm7_COMMON.h"
OUT = pathlib.Path(__file__).resolve().parent.parent / "imxrt1176.h"

WANTED = {"CCM": "CCM", "IOMUXC": "IOMUXC", "IOMUXC_GPR": "IOMUXC_GPR",
          "FLEXSPI1": "FLEXSPI", "FLEXSPI2": "FLEXSPI2",
          "ANADIG_PLL": "ANADIG_PLL", "ANADIG_OSC": "ANADIG_OSC",
          "ENET": "ENET",
          **{f"GPIO{i}": f"GPIO{i}" for i in range(1, 14)}}

# --- CCM clock roots (Task 9: 996 MHz core clock tree) -----------------------
# CCM->CLOCK_ROOT[n].CONTROL is at CCM_BASE + n*0x80 (CONTROL at struct offset 0).
# We emit the roots the 996 MHz bring-up touches.  See SDK BOARD_BootClockRUN /
# clock_root_t enum (fsl_clock.h):  M7=0, Bus=2, M7_Systick=8.
CCM_ROOT_STRIDE = 0x80
CCM_CLOCK_ROOTS = {0: "M7", 2: "BUS", 8: "M7_SYSTICK"}

# ANADIG_PLL / ANADIG_OSC register offsets (from MIMXRT1176_cm7.h peripheral
# struct layouts).  Both blocks share base 0x40C84000 in the analog top.
ANADIG_PLL_REGS = {"ARM_PLL_CTRL": 0x200}   # ARM_PLL_CTRL_REGISTER, offset 0x200
ANADIG_OSC_REGS = {"OSC_24M_CTRL": 0x020}   # 24MHz OSC Control,      offset 0x020

# --- IOMUXC per-pad mux / pad-control registers (Task 11: EVKB pin table) -----
# Offsets from IOMUXC_BASE (0x400E8000), derived from the SDK's pin-mux macros
# in fsl_iomuxc.h.  Each macro `IOMUXC_<PAD>_<SIGNAL>` expands to
#   muxRegister, muxMode, inputRegister, inputDaisy, configRegister
# e.g. IOMUXC_GPIO_AD_04_GPIO9_IO03 = 0x400E811C, 0xA, 0, 0, 0x400E8360
# so SW_MUX_CTL_PAD_GPIO_AD_04 @ +0x11C, SW_PAD_CTL_PAD_GPIO_AD_04 @ +0x360.
# muxMode 0xA (ALT10) selects GPIO9_IO03 (the EVKB User LED D6, GPIO9 bit 3).
IOMUXC_MUX_CTL_REGS = {"GPIO_AD_04": 0x11C}
IOMUXC_PAD_CTL_REGS = {"GPIO_AD_04": 0x360}
# LPUART1 console pins (EVKB VCOM): TX=GPIO_AD_24, RX=GPIO_AD_25.
IOMUXC_MUX_CTL_REGS.update({"GPIO_AD_24": 0x16C, "GPIO_AD_25": 0x170})
IOMUXC_PAD_CTL_REGS.update({"GPIO_AD_24": 0x3B0, "GPIO_AD_25": 0x3B4})
# LPADC1 analog input A0 = GPIO_AD_06 (ADC1_CH0A). Muxed to a non-driving ALT so
# the ADC can tap the pad (per the SDK lpadc example: ALT5 GPIO_MUX3_IO05).
IOMUXC_MUX_CTL_REGS.update({"GPIO_AD_06": 0x124})
IOMUXC_PAD_CTL_REGS.update({"GPIO_AD_06": 0x368})

def parse_bases(txt):
    bases = {}
    for m in re.finditer(r'#define\s+(\w+)_BASE\s+\(([0-9a-fA-Fxu]+)\)', txt):
        try: bases[m.group(1)] = int(m.group(2).rstrip("uU"), 0)
        except ValueError: pass
    return bases

def main():
    bases = parse_bases(SDK.read_text())
    L = ["/* AUTO-GENERATED by tools/gen_imxrt1176_h.py -- do not edit by hand.",
         " * Standalone Teensy-idiom register defs for NXP i.MX RT1176 (CM7). */",
         "#ifndef _imxrt1176_h_", "#define _imxrt1176_h_", "#include <stdint.h>", ""]
    for inst, pfx in sorted(WANTED.items()):
        b = bases.get(inst)
        if b is None: print(f"warn: no base for {inst}", file=sys.stderr); continue
        L.append(f"#define {pfx}_BASE 0x{b:08X}u")
    for i in range(1, 14):
        b = bases.get(f"GPIO{i}")
        if b is None: continue
        L += [f"#define GPIO{i}_DR        (*(volatile uint32_t *)0x{b+0x00:08X}u)",
              f"#define GPIO{i}_GDIR      (*(volatile uint32_t *)0x{b+0x04:08X}u)",
              f"#define GPIO{i}_PSR       (*(volatile uint32_t *)0x{b+0x08:08X}u)",
              f"#define GPIO{i}_DR_SET    (*(volatile uint32_t *)0x{b+0x84:08X}u)",
              f"#define GPIO{i}_DR_CLEAR  (*(volatile uint32_t *)0x{b+0x88:08X}u)",
              f"#define GPIO{i}_DR_TOGGLE (*(volatile uint32_t *)0x{b+0x8C:08X}u)"]
    # --- CCM clock-root CONTROL registers (Task 9) ---------------------------
    ccm = bases.get("CCM")
    if ccm is not None:
        L.append("")
        L.append("/* CCM clock roots: CCM->CLOCK_ROOT[n].CONTROL @ CCM_BASE + n*0x80 */")
        for n, nm in sorted(CCM_CLOCK_ROOTS.items()):
            addr = ccm + n * CCM_ROOT_STRIDE
            L.append(f"#define CCM_CLOCK_ROOT{n}_CONTROL (*(volatile uint32_t *)0x{addr:08X}u) /* {nm} */")
        L += ["#define CCM_CLOCK_ROOT_CONTROL_MUX(x)  (((uint32_t)(x) << 8) & 0x700u)",
              "#define CCM_CLOCK_ROOT_CONTROL_DIV(x)  (((uint32_t)(x) << 0) & 0x0FFu)"]

    # --- ANADIG PLL / OSC registers (Task 9: ARM PLL = 996 MHz, 24M OSC) ------
    apll = bases.get("ANADIG_PLL")
    if apll is not None:
        L.append("")
        for nm, off in sorted(ANADIG_PLL_REGS.items()):
            L.append(f"#define ANADIG_PLL_{nm} (*(volatile uint32_t *)0x{apll+off:08X}u)")
        L += ["#define ANADIG_PLL_ARM_PLL_CTRL_DIV_SELECT(x)   (((uint32_t)(x) << 0) & 0x000000FFu)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_HOLD_RING_OFF   (1u << 12)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_POWERUP         (1u << 13)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ENABLE_CLK      (1u << 14)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_POST_DIV_SEL(x) (((uint32_t)(x) << 15) & 0x00018000u)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_BYPASS          (1u << 17)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_STABLE  (1u << 29)",
              "#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_GATE    (1u << 30)"]
    aosc = bases.get("ANADIG_OSC")
    if aosc is not None:
        for nm, off in sorted(ANADIG_OSC_REGS.items()):
            L.append(f"#define ANADIG_OSC_{nm} (*(volatile uint32_t *)0x{aosc+off:08X}u)")
        L += ["#define ANADIG_OSC_OSC_24M_CTRL_OSC_EN          (1u << 4)",
              "#define ANADIG_OSC_OSC_24M_CTRL_LP_EN           (1u << 2)",
              "#define ANADIG_OSC_OSC_24M_CTRL_OSC_24M_STABLE  (1u << 30)"]

    # --- IOMUXC per-pad mux / pad-ctl registers (Task 11) --------------------
    iomuxc = bases.get("IOMUXC")
    if iomuxc is not None and (IOMUXC_MUX_CTL_REGS or IOMUXC_PAD_CTL_REGS):
        L.append("")
        L.append("/* IOMUXC per-pad mux/pad-control regs (offsets from fsl_iomuxc.h) */")
        for pad, off in sorted(IOMUXC_MUX_CTL_REGS.items()):
            L.append(f"#define IOMUXC_SW_MUX_CTL_PAD_{pad} (*(volatile uint32_t *)0x{iomuxc+off:08X}u)")
        for pad, off in sorted(IOMUXC_PAD_CTL_REGS.items()):
            L.append(f"#define IOMUXC_SW_PAD_CTL_PAD_{pad} (*(volatile uint32_t *)0x{iomuxc+off:08X}u)")

    L += ["", "#define SYST_CSR   (*(volatile uint32_t *)0xE000E010u)",
          "#define SYST_RVR   (*(volatile uint32_t *)0xE000E014u)",
          "#define SYST_CVR   (*(volatile uint32_t *)0xE000E018u)",
          "#define SCB_VTOR   (*(volatile uint32_t *)0xE000ED08u)",
          "#define SCB_ICSR   (*(volatile uint32_t *)0xE000ED04u)",
          "#define SCB_ICSR_PENDSTSET (1u << 26)",
          "#define ARM_DWT_CYCCNT (*(volatile uint32_t *)0xE0001004u)",
          "#define ARM_DWT_CTRL   (*(volatile uint32_t *)0xE0001000u)",
          "#define ARM_DEMCR      (*(volatile uint32_t *)0xE000EDFCu)",
          "#define ARM_DEMCR_TRCENA (1u << 24)"]
    L += ["",
          "/* --- Cortex-M7 NVIC (Task: interrupt infrastructure) --- */",
          "#define NVIC_ISER(n) (*(volatile uint32_t *)(0xE000E100u + ((n) << 2)))",
          "#define NVIC_ICER(n) (*(volatile uint32_t *)(0xE000E180u + ((n) << 2)))",
          "#define NVIC_ISPR(n) (*(volatile uint32_t *)(0xE000E200u + ((n) << 2)))",
          "#define NVIC_ICPR(n) (*(volatile uint32_t *)(0xE000E280u + ((n) << 2)))",
          "#define NVIC_IP(n)   (*(volatile uint8_t  *)(0xE000E400u + (n)))",
          "#define NVIC_ENABLE_IRQ(n)   (NVIC_ISER((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_IS_ENABLED(n)   (NVIC_ISER((n) >> 5) & (1u << ((n) & 31)))",
          "#define NVIC_DISABLE_IRQ(n)  (NVIC_ICER((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_SET_PENDING(n)  (NVIC_ISPR((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_CLEAR_PENDING(n)(NVIC_ICPR((n) >> 5) = (1u << ((n) & 31)))",
          "#define NVIC_SET_PRIORITY(n, p) (NVIC_IP(n) = (uint8_t)(p))"]
    # --- LPUART register blocks + bitfields (Task: Serial1) -----------------
    LPUART_BASES = {1:0x4007C000, 2:0x40080000, 3:0x40084000, 4:0x40088000,
                    5:0x4008C000, 6:0x40090000, 7:0x40094000, 8:0x40098000,
                    9:0x4009C000, 10:0x400A0000, 11:0x40C24000, 12:0x40C28000}
    LPUART_REGS = {"VERID":0x0,"PARAM":0x4,"GLOBAL":0x8,"PINCFG":0xC,"BAUD":0x10,
                   "STAT":0x14,"CTRL":0x18,"DATA":0x1C,"MATCH":0x20,"MODIR":0x24,
                   "FIFO":0x28,"WATER":0x2C}
    L += ["", "/* --- LPUART register blocks (Task: Serial1) --- */"]
    for n, base in sorted(LPUART_BASES.items()):
        for reg, off in LPUART_REGS.items():
            L.append(f"#define LPUART{n}_{reg} (*(volatile uint32_t *)0x{base+off:08X}u)")
    L += ["",
          "/* LPUART bitfields (RT1176 RM / PERI_LPUART.h) */",
          "#define LPUART_STAT_RDRF   (1u << 21)",
          "#define LPUART_STAT_TDRE   (1u << 23)",
          "#define LPUART_STAT_TC     (1u << 22)",
          "#define LPUART_STAT_IDLE   (1u << 20)",
          "#define LPUART_STAT_OR     (1u << 19)",
          "#define LPUART_CTRL_RE     (1u << 18)",
          "#define LPUART_CTRL_TE     (1u << 19)",
          "#define LPUART_CTRL_ILIE   (1u << 20)",
          "#define LPUART_CTRL_RIE    (1u << 21)",
          "#define LPUART_CTRL_TCIE   (1u << 22)",
          "#define LPUART_CTRL_TIE    (1u << 23)",
          "#define LPUART_BAUD_SBR(n)   ((uint32_t)(n) & 0x1FFFu)",
          "#define LPUART_BAUD_OSR(n)   (((uint32_t)(n) & 0x1Fu) << 24)",
          "#define LPUART_BAUD_BOTHEDGE (1u << 17)",
          "#define LPUART_FIFO_RXFE   (1u << 3)",
          "#define LPUART_FIFO_TXFE   (1u << 7)",
          "#define LPUART_WATER_TXWATER(n) ((uint32_t)(n) & 0x3u)",
          "#define LPUART_WATER_RXWATER(n) (((uint32_t)(n) << 16) & 0x30000u)"]
    L += ["",
          "/* LPUART1 console clock + input select (EVKB VCOM) */",
          "#define CCM_CLOCK_ROOT25_CONTROL (*(volatile uint32_t *)0x40CC0C80u)",
          "#define CCM_LPCG86_DIRECT        (*(volatile uint32_t *)0x40CC6AC0u)",
          "#define IOMUXC_LPUART1_TXD_SELECT_INPUT (*(volatile uint32_t *)0x400E8620u)",
          "#define IOMUXC_LPUART1_RXD_SELECT_INPUT (*(volatile uint32_t *)0x400E861Cu)"]
    # --- LPADC (ADC1/ADC2) register blocks + bitfields (Task: analogRead) ---
    ADC_BASES = {1: 0x40050000, 2: 0x40054000}
    ADC_REGS = {"VERID":0x0,"PARAM":0x4,"CTRL":0x10,"STAT":0x14,"IE":0x18,"DE":0x1C,
                "CFG":0x20,"PAUSE":0x24,"FCTRL":0x30,"SWTRIG":0x34,
                "TCTRL0":0xC0,"CMDL1":0x100,"CMDH1":0x104,"RESFIFO":0x300}
    L += ["", "/* --- LPADC register blocks (Task: analogRead) --- */"]
    for n, base in sorted(ADC_BASES.items()):
        for reg, off in ADC_REGS.items():
            L.append(f"#define ADC{n}_{reg} (*(volatile uint32_t *)0x{base+off:08X}u)")
    L += ["",
          "/* LPADC bitfields (RT1176 RM / PERI_ADC.h) */",
          "#define ADC_CTRL_ADCEN   (1u << 0)",
          "#define ADC_CTRL_RST     (1u << 1)",
          "#define ADC_CTRL_RSTFIFO (1u << 8)",
          "#define ADC_STAT_RDY     (1u << 0)",
          "#define ADC_STAT_FOF     (1u << 1)",
          "#define ADC_IE_FWMIE     (1u << 0)",
          "#define ADC_CMDL_ADCH(x)   ((uint32_t)(x) & 0x1Fu)",
          "#define ADC_CMDL_CSCALE    (1u << 13)  /* 1 = full scale (SDK default); 0 = input scaled 30/64 */",
          "#define ADC_CMDH_STS(x)    (((uint32_t)(x) & 0x7u) << 8)  /* sample time: 0=3.5 ADCK .. 7=131.5 ADCK */",
          "#define ADC_TCTRL_TCMD(x)  (((uint32_t)(x) & 0xFu) << 24)",
          "#define ADC_FCTRL_FWMARK(x)(((uint32_t)(x) & 0xFu) << 16)",
          "#define ADC_CFG_PWRSEL(x)  (((uint32_t)(x) & 0x3u) << 4)",
          "#define ADC_CFG_REFSEL(x)  (((uint32_t)(x) & 0x3u) << 6)",
          "#define ADC_RESFIFO_D      (0xFFFFu)",
          "#define ADC_RESFIFO_VALID  (1u << 31)",
          "",
          "/* LPADC clock roots + LPCG gates */",
          "#define CCM_CLOCK_ROOT9_CONTROL  (*(volatile uint32_t *)0x40CC0480u)",
          "#define CCM_CLOCK_ROOT10_CONTROL (*(volatile uint32_t *)0x40CC0500u)",
          "#define CCM_LPCG55_DIRECT (*(volatile uint32_t *)0x40CC66E0u)",
          "#define CCM_LPCG56_DIRECT (*(volatile uint32_t *)0x40CC6700u)"]
    L += ["",
          "/* --- DAC12 (12-bit DAC, base 0x40064000, IRQ 63, LPCG 57; Task: analogWriteDAC0) ---",
          " * PERI_DAC.h / RM ch.89. RT1170 chip-specifics (RM 89.1): VREFH is the ONLY",
          " * reference (CR.DACRFS must be 1), no HW trigger, no ITRM register, IREF2/PTAT",
          " * current ref unavailable. DATA is write-only on silicon. */",
          "#define DAC_VERID (*(volatile uint32_t *)0x40064000u)",
          "#define DAC_PARAM (*(volatile uint32_t *)0x40064004u)   /* FIFOSZ[2:0]=0b011 -> 16-word FIFO */",
          "#define DAC_DATA  (*(volatile uint32_t *)0x40064008u)   /* write-only: DATA0[11:0] */",
          "#define DAC_CR    (*(volatile uint32_t *)0x4006400Cu)",
          "#define DAC_PTR   (*(volatile uint32_t *)0x40064010u)",
          "#define DAC_CR2   (*(volatile uint32_t *)0x40064014u)",
          "#define DAC_PARAM_FIFOSZ_MASK   0x7u",
          "#define DAC_DATA_DATA0_MASK     0xFFFu",
          "#define DAC_CR_FULLF_MASK       0x1u        /* ro: FIFO full */",
          "#define DAC_CR_NEMPTF_MASK      0x2u        /* ro: one datum left */",
          "#define DAC_CR_WMF_MASK         0x4u        /* ro: remaining < WML */",
          "#define DAC_CR_UDFF_MASK        0x8u        /* w1c: trigger underflow */",
          "#define DAC_CR_OVFF_MASK        0x10u       /* w1c: FIFO overflow */",
          "#define DAC_CR_FULLIE_MASK      0x100u",
          "#define DAC_CR_EMPTIE_MASK      0x200u",
          "#define DAC_CR_WTMIE_MASK       0x400u",
          "#define DAC_CR_SWTRG_MASK       0x1000u     /* self-clearing */",
          "#define DAC_CR_TRGSEL_MASK      0x2000u     /* 1 = SW trigger (only option on RT1170) */",
          "#define DAC_CR_DACRFS_MASK      0x4000u     /* MUST be 1 on RT1170 (VREFH) */",
          "#define DAC_CR_DACEN_MASK       0x8000u",
          "#define DAC_CR_FIFOEN_MASK      0x10000u",
          "#define DAC_CR_SWMD_MASK        0x20000u",
          "#define DAC_CR_UVIE_MASK        0x40000u",
          "#define DAC_CR_FIFORST_MASK     0x200000u   /* self-clearing */",
          "#define DAC_CR_SWRST_MASK       0x400000u   /* self-clearing */",
          "#define DAC_CR_DMAEN_MASK       0x800000u",
          "#define DAC_CR_WML_SHIFT        24",
          "#define DAC_CR_WML_MASK         0xFF000000u",
          "#define DAC_PTR_DACWFP_MASK     0xFFu",
          "#define DAC_PTR_DACRFP_SHIFT    16",
          "#define DAC_PTR_DACRFP_MASK     0xFF0000u",
          "#define DAC_CR2_BFEN_MASK       0x1u        /* opamp buffer */",
          "#define DAC_CR2_OEN_MASK        0x2u        /* buffer bypassed */",
          "#define DAC_CR2_BFMS_MASK       0x4u",
          "#define DAC_CR2_BFHS_MASK       0x8u",
          "#define DAC_CR2_IREF1_MASK      0x20u       /* ZTC current ref */",
          "#define DAC_CR2_IREF_MASK       0x40u       /* internal current ref (SDK default) */",
          "/* DAC clock gate: kCLOCK_Dac = LPCG 57 (0x40CC6000 + 57*0x20). */",
          "#define CCM_LPCG57_DIRECT (*(volatile uint32_t *)0x40CC6720u)"]
    L += ["",
          "/* IOMUXC_GPR FlexRAM bank-config registers (base 0x400E4000) */",
          "#define IOMUXC_GPR_GPR14 (*(volatile uint32_t *)0x400E4038u)",
          "#define IOMUXC_GPR_GPR16 (*(volatile uint32_t *)0x400E4040u)",
          "#define IOMUXC_GPR_GPR17 (*(volatile uint32_t *)0x400E4044u)  /* FLEXRAM_BANK_CFG_LOW  (banks 0-7)  */",
          "#define IOMUXC_GPR_GPR18 (*(volatile uint32_t *)0x400E4048u)  /* FLEXRAM_BANK_CFG_HIGH (banks 8-15) */"]
    L += ["",
          "/* SRC (System Reset Controller, base 0x40C04000) - dual-core reset control.",
          " * SRSR bitmap (nxp PERI_SRC.h): bit2 M7_LOCKUP, bit12 M4_LOCKUP_M7, bit0/16 POR. */",
          "#define SRC_SRMR (*(volatile uint32_t *)0x40C04004u)  /* [7:6] M4LOCKUP_RESET_MODE, [11:10] M4REQ_RESET_MODE */",
          "#define SRC_SRSR (*(volatile uint32_t *)0x40C04010u)  /* reset status (write 1 to clear) */"]
    L += ["",
          "/* LPI2C1 (Arduino-header I2C master), base 0x40104000 */",
          "#define LPI2C1_MCR    (*(volatile uint32_t *)0x40104010u)",
          "#define LPI2C1_MSR    (*(volatile uint32_t *)0x40104014u)",
          "#define LPI2C1_MIER   (*(volatile uint32_t *)0x40104018u)",
          "#define LPI2C1_MCFGR1 (*(volatile uint32_t *)0x40104024u)",
          "#define LPI2C1_MCCR0  (*(volatile uint32_t *)0x40104048u)",
          "#define LPI2C1_MFCR   (*(volatile uint32_t *)0x40104058u)",
          "#define LPI2C1_MTDR   (*(volatile uint32_t *)0x40104060u)",
          "#define LPI2C1_MRDR   (*(volatile uint32_t *)0x40104070u)",
          "/* LPI2C1 clock: CCM_CLOCK_ROOT37 + LPCG98 */",
          "#define CCM_CLOCK_ROOT37_CONTROL (*(volatile uint32_t *)0x40CC1280u)",
          "#define CCM_LPCG98_DIRECT        (*(volatile uint32_t *)0x40CC6C40u)",
          "/* LPI2C1 pins: SCL=GPIO_AD_08, SDA=GPIO_AD_09 (ALT1) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_08 (*(volatile uint32_t *)0x400E812Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_09 (*(volatile uint32_t *)0x400E8130u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_08 (*(volatile uint32_t *)0x400E8370u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_09 (*(volatile uint32_t *)0x400E8374u)",
          "#define IOMUXC_LPI2C1_SCL_SELECT_INPUT   (*(volatile uint32_t *)0x400E85ACu)",
          "#define IOMUXC_LPI2C1_SDA_SELECT_INPUT   (*(volatile uint32_t *)0x400E85B0u)"]
    L += ["",
          "/* LPI2C1 slave register block */",
          "#define LPI2C1_SCR    (*(volatile uint32_t *)0x40104110u)",
          "#define LPI2C1_SSR    (*(volatile uint32_t *)0x40104114u)",
          "#define LPI2C1_SIER   (*(volatile uint32_t *)0x40104118u)",
          "#define LPI2C1_SCFGR1 (*(volatile uint32_t *)0x40104124u)",
          "#define LPI2C1_SCFGR2 (*(volatile uint32_t *)0x40104128u)",
          "#define LPI2C1_SAMR   (*(volatile uint32_t *)0x40104140u)",
          "#define LPI2C1_SASR   (*(volatile uint32_t *)0x40104150u)",
          "#define LPI2C1_STAR   (*(volatile uint32_t *)0x40104154u)",
          "#define LPI2C1_STDR   (*(volatile uint32_t *)0x40104160u)",
          "#define LPI2C1_SRDR   (*(volatile uint32_t *)0x40104170u)",
          "/* LPI2C2 (QEMU loopback slave), base 0x40108000 */",
          "#define LPI2C2_MCR    (*(volatile uint32_t *)0x40108010u)",
          "#define LPI2C2_MSR    (*(volatile uint32_t *)0x40108014u)",
          "#define LPI2C2_MIER   (*(volatile uint32_t *)0x40108018u)",
          "#define LPI2C2_MCFGR1 (*(volatile uint32_t *)0x40108024u)",
          "#define LPI2C2_MCCR0  (*(volatile uint32_t *)0x40108048u)",
          "#define LPI2C2_MTDR   (*(volatile uint32_t *)0x40108060u)",
          "#define LPI2C2_MRDR   (*(volatile uint32_t *)0x40108070u)",
          "#define LPI2C2_SCR    (*(volatile uint32_t *)0x40108110u)",
          "#define LPI2C2_SSR    (*(volatile uint32_t *)0x40108114u)",
          "#define LPI2C2_SIER   (*(volatile uint32_t *)0x40108118u)",
          "#define LPI2C2_SCFGR1 (*(volatile uint32_t *)0x40108124u)",
          "#define LPI2C2_SCFGR2 (*(volatile uint32_t *)0x40108128u)",
          "#define LPI2C2_SAMR   (*(volatile uint32_t *)0x40108140u)",
          "#define LPI2C2_SASR   (*(volatile uint32_t *)0x40108150u)",
          "#define LPI2C2_STAR   (*(volatile uint32_t *)0x40108154u)",
          "#define LPI2C2_STDR   (*(volatile uint32_t *)0x40108160u)",
          "#define LPI2C2_SRDR   (*(volatile uint32_t *)0x40108170u)",
          "/* LPI2C2 clock: CCM_CLOCK_ROOT38 + LPCG99 */",
          "#define CCM_CLOCK_ROOT38_CONTROL (*(volatile uint32_t *)0x40CC1300u)",
          "#define CCM_LPCG99_DIRECT        (*(volatile uint32_t *)0x40CC6C60u)"]
    L += ["",
          "/* LPSPI1 (Arduino-header SPI master), base 0x40114000 */",
          "#define LPSPI1_CR     (*(volatile uint32_t *)0x40114010u)",
          "#define LPSPI1_SR     (*(volatile uint32_t *)0x40114014u)",
          "#define LPSPI1_DER    (*(volatile uint32_t *)0x4011401Cu)",
          "#define LPSPI1_CFGR1  (*(volatile uint32_t *)0x40114024u)",
          "#define LPSPI1_CCR    (*(volatile uint32_t *)0x40114040u)",
          "#define LPSPI1_FCR    (*(volatile uint32_t *)0x40114058u)",
          "#define LPSPI1_TCR    (*(volatile uint32_t *)0x40114060u)",
          "#define LPSPI1_TDR    (*(volatile uint32_t *)0x40114064u)",
          "#define LPSPI1_RSR    (*(volatile uint32_t *)0x40114070u)",
          "#define LPSPI1_RDR    (*(volatile uint32_t *)0x40114074u)",
          "/* LPSPI1 clock: CCM_CLOCK_ROOT43 + LPCG104 (mux 0 = 24 MHz) */",
          "#define CCM_CLOCK_ROOT43_CONTROL (*(volatile uint32_t *)0x40CC1580u)",
          "#define CCM_LPCG104_DIRECT       (*(volatile uint32_t *)0x40CC6D00u)",
          "/* LPSPI1 pins: SCK=GPIO_AD_28, SOUT=GPIO_AD_30, SIN=GPIO_AD_31 (ALT0) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_28 (*(volatile uint32_t *)0x400E817Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_30 (*(volatile uint32_t *)0x400E8184u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_31 (*(volatile uint32_t *)0x400E8188u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_28 (*(volatile uint32_t *)0x400E83C0u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_30 (*(volatile uint32_t *)0x400E83C8u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_31 (*(volatile uint32_t *)0x400E83CCu)",
          "#define IOMUXC_LPSPI1_SCK_SELECT_INPUT   (*(volatile uint32_t *)0x400E85D0u)",
          "#define IOMUXC_LPSPI1_SDO_SELECT_INPUT   (*(volatile uint32_t *)0x400E85D8u)",
          "#define IOMUXC_LPSPI1_SDI_SELECT_INPUT   (*(volatile uint32_t *)0x400E85D4u)"]
    L += ['''
/* LPSPI register-block overlay (for the newdigate/SPI library's port()
 * accessor).  Layout matches cores/teensy4/imxrt.h IMXRT_LPSPI_t; verified
 * against the flat LPSPI1_* offsets above (base 0x40114000). */
typedef struct {
	volatile uint32_t VERID;    // 0x00
	volatile uint32_t PARAM;    // 0x04
	volatile uint32_t unused08; // 0x08
	volatile uint32_t unused0C; // 0x0C
	volatile uint32_t CR;       // 0x10
	volatile uint32_t SR;       // 0x14
	volatile uint32_t IER;      // 0x18
	volatile uint32_t DER;      // 0x1C
	volatile uint32_t CFGR0;    // 0x20
	volatile uint32_t CFGR1;    // 0x24
	volatile uint32_t unused28; // 0x28
	volatile uint32_t unused2C; // 0x2C
	volatile uint32_t DMR0;     // 0x30
	volatile uint32_t DMR1;     // 0x34
	volatile uint32_t unused38; // 0x38
	volatile uint32_t unused3C; // 0x3C
	volatile uint32_t CCR;      // 0x40
	volatile uint32_t unused44[5]; // 0x44..0x54
	volatile uint32_t FCR;      // 0x58
	volatile uint32_t FSR;      // 0x5C
	volatile uint32_t TCR;      // 0x60
	volatile uint32_t TDR;      // 0x64
	volatile uint32_t unused68; // 0x68
	volatile uint32_t unused6C; // 0x6C
	volatile uint32_t RSR;      // 0x70
	volatile uint32_t RDR;      // 0x74
} IMXRT_LPSPI_t;
#define IMXRT_LPSPI1_ADDRESS 0x40114000
'''.rstrip("\n")]
    L += ['''
/* LPI2C register-block overlay (for the newdigate/Wire library's port()
 * accessor).  Layout matches cores/teensy4/imxrt.h IMXRT_LPI2C_t; verified
 * against the flat LPI2C1_* offsets above.  Master block 0x10..0x70, then a
 * gap, slave block 0x110..0x170.  Same layout at all 3 bases (LPI2C1
 * 0x40104000, LPI2C2 0x40108000, LPI2C5 0x40C34000). */
typedef struct {
	volatile uint32_t VERID;        // 0x00
	volatile uint32_t PARAM;        // 0x04
	volatile uint32_t unused08;     // 0x08
	volatile uint32_t unused0C;     // 0x0C
	volatile uint32_t MCR;          // 0x10
	volatile uint32_t MSR;          // 0x14
	volatile uint32_t MIER;         // 0x18
	volatile uint32_t MDER;         // 0x1C
	volatile uint32_t MCFGR0;       // 0x20
	volatile uint32_t MCFGR1;       // 0x24
	volatile uint32_t MCFGR2;       // 0x28
	volatile uint32_t MCFGR3;       // 0x2C
	volatile uint32_t unused30[4];  // 0x30..0x3C
	volatile uint32_t MDMR;         // 0x40
	volatile uint32_t unused44;     // 0x44
	volatile uint32_t MCCR0;        // 0x48
	volatile uint32_t unused4C;     // 0x4C
	volatile uint32_t MCCR1;        // 0x50
	volatile uint32_t unused54;     // 0x54
	volatile uint32_t MFCR;         // 0x58
	volatile uint32_t MFSR;         // 0x5C
	volatile uint32_t MTDR;         // 0x60
	volatile uint32_t unused64[3];  // 0x64..0x6C
	volatile uint32_t MRDR;         // 0x70
	volatile uint32_t unused74[39]; // 0x74..0x10C
	volatile uint32_t SCR;          // 0x110
	volatile uint32_t SSR;          // 0x114
	volatile uint32_t SIER;         // 0x118
	volatile uint32_t SDER;         // 0x11C
	volatile uint32_t unused120;    // 0x120
	volatile uint32_t SCFGR1;       // 0x124
	volatile uint32_t SCFGR2;       // 0x128
	volatile uint32_t unused12C[5]; // 0x12C..0x13C
	volatile uint32_t SAMR;         // 0x140
	volatile uint32_t unused144[3]; // 0x144..0x14C
	volatile uint32_t SASR;         // 0x150
	volatile uint32_t STAR;         // 0x154
	volatile uint32_t unused158[2]; // 0x158..0x15C
	volatile uint32_t STDR;         // 0x160
	volatile uint32_t unused164[3]; // 0x164..0x16C
	volatile uint32_t SRDR;         // 0x170
} IMXRT_LPI2C_t;
#define IMXRT_LPI2C1_ADDRESS 0x40104000
#define IMXRT_LPI2C2_ADDRESS 0x40108000
#define IMXRT_LPI2C5_ADDRESS 0x40C34000
'''.rstrip("\n")]
    # --- USDHC (SDIO / SD-card) — for the SdFat SdioTeensy __IMXRT1176__ port --
    # microSD slot on the MIMXRT1170-EVKB (socket J15) = USDHC1 @ 0x40418000.
    # Pins GPIO_SD_B1_00..05 (ALT0); clock root 58 (SYS_PLL2_PFD2/2 ~198 MHz);
    # gate LPCG117; IRQ 133.  Addresses verified against the generator's own
    # IOMUXC scheme (AD_35 mux ends 0x198 / pad 0x3DC, so SD_B1_00 follows).
    L += ["",
          "/* USDHC1 microSD pins (EVKB J15): CMD/CLK/DATA0-3 = GPIO_SD_B1_00..05, ALT0 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_00 (*(volatile uint32_t *)0x400E819Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_01 (*(volatile uint32_t *)0x400E81A0u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_02 (*(volatile uint32_t *)0x400E81A4u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_03 (*(volatile uint32_t *)0x400E81A8u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_04 (*(volatile uint32_t *)0x400E81ACu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_SD_B1_05 (*(volatile uint32_t *)0x400E81B0u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_00 (*(volatile uint32_t *)0x400E83E0u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_01 (*(volatile uint32_t *)0x400E83E4u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_02 (*(volatile uint32_t *)0x400E83E8u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_03 (*(volatile uint32_t *)0x400E83ECu)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_04 (*(volatile uint32_t *)0x400E83F0u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_SD_B1_05 (*(volatile uint32_t *)0x400E83F4u)",
          "/* USDHC1 clock root 58 (SYS_PLL2_PFD2 / 2) + gate LPCG117 */",
          "#define CCM_CLOCK_ROOT58_CONTROL (*(volatile uint32_t *)0x40CC1D00u)",
          "#define CCM_LPCG117_DIRECT       (*(volatile uint32_t *)0x40CC6EA0u)"]
    L += ['''
/* USDHC register-block overlay (for the SdFat SdioTeensy __IMXRT1176__ port).
 * Layout matches cores/teensy4/imxrt.h IMXRT_USDHC_t; only the base addresses
 * differ from the 1062 (0x40418000/0x4041C000 vs 0x402C0000/0x402C4000). */
typedef struct {
	volatile uint32_t DS_ADDR;              // 0x00
	volatile uint32_t BLK_ATT;              // 0x04
	volatile uint32_t CMD_ARG;              // 0x08
	volatile uint32_t CMD_XFR_TYP;          // 0x0C
	volatile uint32_t CMD_RSP0;             // 0x10
	volatile uint32_t CMD_RSP1;             // 0x14
	volatile uint32_t CMD_RSP2;             // 0x18
	volatile uint32_t CMD_RSP3;             // 0x1C
	volatile uint32_t DATA_BUFF_ACC_PORT;   // 0x20
	volatile uint32_t PRES_STATE;           // 0x24
	volatile uint32_t PROT_CTRL;            // 0x28
	volatile uint32_t SYS_CTRL;             // 0x2C
	volatile uint32_t INT_STATUS;           // 0x30
	volatile uint32_t INT_STATUS_EN;        // 0x34
	volatile uint32_t INT_SIGNAL_EN;        // 0x38
	volatile uint32_t AUTOCMD12_ERR_STATUS; // 0x3C
	volatile uint32_t HOST_CTRL_CAP;        // 0x40
	volatile uint32_t WTMK_LVL;             // 0x44
	volatile uint32_t MIX_CTRL;             // 0x48
	uint32_t unused1;                       // 0x4C
	volatile uint32_t FORCE_EVENT;          // 0x50
	volatile uint32_t ADMA_ERR_STATUS;      // 0x54
	volatile uint32_t ADMA_SYS_ADDR;        // 0x58
	uint32_t unused2;                       // 0x5C
	volatile uint32_t DLL_CTRL;             // 0x60
	volatile uint32_t DLL_STATUS;           // 0x64
	volatile uint32_t CLK_TUNE_CTRL_STATUS; // 0x68
	uint32_t unused3[21];                   // 0x6C..0xBC
	volatile uint32_t VEND_SPEC;            // 0xC0
	volatile uint32_t MMC_BOOT;             // 0xC4
	volatile uint32_t VEND_SPEC2;           // 0xC8
	volatile uint32_t TUNING_CTRL;          // 0xCC
} IMXRT_USDHC_t;
#define IMXRT_USDHC1_ADDRESS 0x40418000
#define IMXRT_USDHC2_ADDRESS 0x4041C000
#define IMXRT_USDHC1 (*(IMXRT_USDHC_t *)IMXRT_USDHC1_ADDRESS)
#define IMXRT_USDHC2 (*(IMXRT_USDHC_t *)IMXRT_USDHC2_ADDRESS)
'''.rstrip("\n")]
    for _n in (1, 2):
        for _reg in ("DS_ADDR","BLK_ATT","CMD_ARG","CMD_XFR_TYP","CMD_RSP0","CMD_RSP1",
                     "CMD_RSP2","CMD_RSP3","DATA_BUFF_ACC_PORT","PRES_STATE","PROT_CTRL",
                     "SYS_CTRL","INT_STATUS","INT_STATUS_EN","INT_SIGNAL_EN",
                     "AUTOCMD12_ERR_STATUS","HOST_CTRL_CAP","WTMK_LVL","MIX_CTRL",
                     "FORCE_EVENT","ADMA_ERR_STATUS","ADMA_SYS_ADDR","DLL_CTRL",
                     "DLL_STATUS","CLK_TUNE_CTRL_STATUS","VEND_SPEC","MMC_BOOT",
                     "VEND_SPEC2","TUNING_CTRL"):
            L.append(f"#define USDHC{_n}_{_reg} (IMXRT_USDHC{_n}.{_reg})")
    L += ["",
          "/* Digital header GPIO bases (GPIO8/9/11/12_BASE already defined above) */",
          "/* Arduino-header pin pads (GPIO ALT = 0xA) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_10 (*(volatile uint32_t *)0x400E823Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_11 (*(volatile uint32_t *)0x400E8240u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_12 (*(volatile uint32_t *)0x400E8244u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_10 (*(volatile uint32_t *)0x400E8480u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_11 (*(volatile uint32_t *)0x400E8484u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_12 (*(volatile uint32_t *)0x400E8488u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_LPSR_04 (*(volatile uint32_t *)0x40C08010u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_LPSR_05 (*(volatile uint32_t *)0x40C08014u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_LPSR_04 (*(volatile uint32_t *)0x40C08050u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_LPSR_05 (*(volatile uint32_t *)0x40C08054u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_00 (*(volatile uint32_t *)0x400E810Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_01 (*(volatile uint32_t *)0x400E8110u)",
          "/* IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_04 already defined above */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_05 (*(volatile uint32_t *)0x400E8120u)",
          "/* IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_06 already defined above */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_07 (*(volatile uint32_t *)0x400E8128u)",
          "/* IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_08/09 already defined above (LPI2C1 block) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_10 (*(volatile uint32_t *)0x400E8134u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_11 (*(volatile uint32_t *)0x400E8138u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_12 (*(volatile uint32_t *)0x400E813Cu)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_13 (*(volatile uint32_t *)0x400E8140u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_14 (*(volatile uint32_t *)0x400E8144u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_29 (*(volatile uint32_t *)0x400E8180u)",
          "/* IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_28/30/31 already defined above (LPSPI1 block) */",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_00 (*(volatile uint32_t *)0x400E8350u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_01 (*(volatile uint32_t *)0x400E8354u)",
          "/* IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_04 already defined above */",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_05 (*(volatile uint32_t *)0x400E8364u)",
          "/* IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_06 already defined above */",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_07 (*(volatile uint32_t *)0x400E836Cu)",
          "/* IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_08/09 already defined above (LPI2C1 block) */",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_10 (*(volatile uint32_t *)0x400E8378u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_11 (*(volatile uint32_t *)0x400E837Cu)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_12 (*(volatile uint32_t *)0x400E8380u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_13 (*(volatile uint32_t *)0x400E8384u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_14 (*(volatile uint32_t *)0x400E8388u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_29 (*(volatile uint32_t *)0x400E83C4u)",
          "/* IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_28/30/31 already defined above (LPSPI1 block) */"]
    L += ["/* FlexPWM (analogWrite): module bases + per-module clock gates */",
          "#define FLEXPWM1_BASE 0x4018C000u",
          "#define FLEXPWM2_BASE 0x40190000u",
          "#define FLEXPWM3_BASE 0x40194000u",
          "#define FLEXPWM4_BASE 0x40198000u",
          "#define CCM_LPCG79_DIRECT (*(volatile uint32_t *)0x40CC69E0u)  /* FlexPWM1 */",
          "#define CCM_LPCG81_DIRECT (*(volatile uint32_t *)0x40CC6A20u)  /* FlexPWM3 */"]
    L += ['''
/* ---- PIT1 (Periodic Interrupt Timer): 4 channels, combined IRQ 155 ------ */
#define PIT1_BASE          0x400D8000u
#define PIT1_MCR           (*(volatile uint32_t *)(PIT1_BASE + 0x00u))
#define PIT1_MCR_MDIS      (1u << 1)         /* module disable (clear to enable) */
typedef struct {
    volatile uint32_t LDVAL;    /* +0x0 load value                */
    volatile uint32_t CVAL;     /* +0x4 current value (read-only) */
    volatile uint32_t TCTRL;    /* +0x8 timer control             */
    volatile uint32_t TFLG;     /* +0xC timer flag (W1C)          */
} pit_channel_t;
#define PIT1_CHANNEL       ((pit_channel_t *)(PIT1_BASE + 0x100u))
#define PIT_TCTRL_TEN      (1u << 0)         /* timer enable           */
#define PIT_TCTRL_TIE      (1u << 1)         /* timer interrupt enable */
#define PIT_TFLG_TIF       (1u << 0)         /* timeout flag (W1C)     */
/* PIT1 clock gate: CCM LPCG62 DIRECT (kCLOCK_Pit1=62 -> 0x6000 + 62*0x20). */
#define CCM_LPCG62_DIRECT  (*(volatile uint32_t *)0x40CC67C0u)

/* ---- USB_OTG1 (ChipIdea/EHCI device controller) + USBPHY1 -------------------
 * Same IP as imxrt1062, so cores/teensy4/usb.c ports verbatim; only the base
 * changes (1062 0x402E0000 -> 0x40430000). Device register window at base+0x140.
 * Register/bit names match Teensy so the port needs no renaming. IRQ = 136. */
#define USB_OTG1_BASE          0x40430000u
#define USB1_USBCMD            (*(volatile uint32_t *)(USB_OTG1_BASE + 0x140))
#define USB1_USBSTS            (*(volatile uint32_t *)(USB_OTG1_BASE + 0x144))
#define USB1_USBINTR           (*(volatile uint32_t *)(USB_OTG1_BASE + 0x148))
#define USB1_DEVICEADDR        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x154))
#define USB1_ENDPOINTLISTADDR  (*(volatile uint32_t *)(USB_OTG1_BASE + 0x158))
#define USB1_BURSTSIZE         (*(volatile uint32_t *)(USB_OTG1_BASE + 0x160))
#define USB1_PORTSC1           (*(volatile uint32_t *)(USB_OTG1_BASE + 0x184))
#define USB1_USBMODE           (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1A8))
#define USB1_ENDPTSETUPSTAT    (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1AC))
#define USB1_ENDPTPRIME        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1B0))
#define USB1_ENDPTFLUSH        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1B4))
#define USB1_ENDPTSTATUS       (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1B8))
#define USB1_ENDPTCOMPLETE     (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1BC))
#define USB1_ENDPTCTRL0        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1C0))
#define USB1_ENDPTCTRL1        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1C4))
#define USB1_ENDPTCTRL2        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1C8))
#define USB1_ENDPTCTRL3        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1CC))
#define USB1_ENDPTCTRL4        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1D0))
#define USB1_ENDPTCTRL5        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1D4))
#define USB1_ENDPTCTRL6        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1D8))
#define USB1_ENDPTCTRL7        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x1DC))

/* USB GPTIMER0 — general-purpose one-shot; usb_serial TX auto-flush (Phase 2). */
#define USB1_GPTIMER0LD        (*(volatile uint32_t *)(USB_OTG1_BASE + 0x080))
#define USB1_GPTIMER0CTRL      (*(volatile uint32_t *)(USB_OTG1_BASE + 0x084))
/* USB_USBSTS_TI0 already defined below (USBSTS/USBINTR bit masks block). */
#define USB_USBINTR_TIE0          ((uint32_t)(1u<<24))
#define USB_GPTIMERCTRL_GPTRUN    ((uint32_t)(1u<<31))
#define USB_GPTIMERCTRL_GPTRST    ((uint32_t)(1u<<30))

/* D-cache is OFF in this core (Phase-1 HW-confirmed) → cache maintenance is a
 * no-op.  Provided so the teensy4 usb_serial.c port compiles verbatim.  If a
 * future build enables the D-cache, replace these with real CMSIS operations. */
static inline void arm_dcache_delete(void *addr, uint32_t size) { (void)addr; (void)size; }
static inline void arm_dcache_flush_delete(void *addr, uint32_t size) { (void)addr; (void)size; }

#define USBPHY1_BASE           0x40434000u
#define USBPHY1_PWD            (*(volatile uint32_t *)(USBPHY1_BASE + 0x00))
#define USBPHY1_CTRL           (*(volatile uint32_t *)(USBPHY1_BASE + 0x30))
#define USBPHY1_CTRL_SET       (*(volatile uint32_t *)(USBPHY1_BASE + 0x34))
#define USBPHY1_CTRL_CLR       (*(volatile uint32_t *)(USBPHY1_BASE + 0x38))
#define USBPHY1_PLL_SIC        (*(volatile uint32_t *)(USBPHY1_BASE + 0xA0))
#define USBPHY1_PLL_SIC_SET    (*(volatile uint32_t *)(USBPHY1_BASE + 0xA4))
#define USBPHY1_PLL_SIC_CLR    (*(volatile uint32_t *)(USBPHY1_BASE + 0xA8))
#define CCM_LPCG115_DIRECT     (*(volatile uint32_t *)0x40CC6E60u)   /* USB (kCLOCK_Usb=115) */
/* USBCMD / USBSTS / USBINTR / USBMODE / DEVICEADDR / ENDPTCTRL bit masks */
#define USB_USBCMD_RST         (1u << 1)
#define USB_USBCMD_RS          (1u << 0)
#define USB_USBCMD_SUTW        (1u << 13)
#define USB_USBCMD_ATDTW       (1u << 14)
#define USB_USBSTS_TI1         (1u << 25)
#define USB_USBSTS_TI0         (1u << 24)
#define USB_USBSTS_SLI         (1u << 8)
#define USB_USBSTS_SRI         (1u << 7)
#define USB_USBSTS_URI         (1u << 6)
#define USB_USBSTS_PCI         (1u << 2)
#define USB_USBSTS_UEI         (1u << 1)
#define USB_USBSTS_UI          (1u << 0)
#define USB_USBINTR_SLE        (1u << 8)
#define USB_USBINTR_SRE        (1u << 7)
#define USB_USBINTR_URE        (1u << 6)
#define USB_USBINTR_PCE        (1u << 2)
#define USB_USBINTR_UEE        (1u << 1)
#define USB_USBINTR_UE         (1u << 0)
#define USB_USBMODE_SLOM       (1u << 3)
#define USB_USBMODE_CM(n)      (((n) & 0x03u) << 0)
#define USB_USBMODE_CM_MASK    (0x03u)
#define USB_DEVICEADDR_USBADR(n) (((n) & 0x7Fu) << 25)
#define USB_DEVICEADDR_USBADRA (1u << 24)
#define USB_ENDPTCTRL_TXS      (1u << 16)
#define USB_ENDPTCTRL_RXS      (1u << 0)
#define USB_PORTSC1_HSP        (1u << 9)
#define USB_PORTSC1_PR         (1u << 8)
/* USBPHY CTRL / PWD / PLL_SIC bit masks (PLL_SIC values from SDK PERI_USBPHY.h) */
#define USBPHY_CTRL_SFTRST     (1u << 31)
#define USBPHY_CTRL_CLKGATE    (1u << 30)
#define USBPHY_CTRL_ENHOSTDISCONDETECT (1u << 1)  /* host: HS disconnect detector (USBHost_t36 ehci isr) */
#define USBPHY_PWD_RXPWDRX     (1u << 20)
#define USBPHY_PWD_RXPWDDIFF   (1u << 19)
#define USBPHY_PWD_RXPWD1PT1   (1u << 18)
#define USBPHY_PWD_RXPWDENV    (1u << 17)
#define USBPHY_PWD_TXPWDV2I    (1u << 12)
#define USBPHY_PWD_TXPWDIBIAS  (1u << 11)
#define USBPHY_PWD_TXPWDFS     (1u << 10)
#define USBPHY_PLL_SIC_PLL_EN_USB_CLKS  (0x40u)
#define USBPHY_PLL_SIC_PLL_POWER        (0x1000u)
#define USBPHY_PLL_SIC_PLL_BYPASS       (0x10000u)
#define USBPHY_PLL_SIC_PLL_REG_ENABLE   (0x200000u)
#define USBPHY_PLL_SIC_PLL_DIV_SEL(n)   (((n) & 0x7u) << 22)
#define USBPHY_PLL_SIC_PLL_DIV_SEL_MASK (0x1C00000u)
#define USBPHY_PLL_SIC_PLL_LOCK         (0x80000000u)

/* DMA structures (USB dQH/dTD/buffers) -> .dmabuffers (OCRAM). */
#ifndef DMAMEM
#define DMAMEM __attribute__((section(".dmabuffers"), used))
#endif
'''.rstrip("\n")]
    L += ['''
/* ---- USB_OTG2 (ChipIdea/EHCI HOST controller) + USBPHY2 --------------------
 * Host-role twin of USB_OTG1 above, added for the USBHost_t36 port.  That
 * library's utility/imxrt_usbhs.h maps USBHS_* -> USB2_* verbatim, exactly as
 * on imxrt1062 where USB2/USBPHY2 are likewise the host controller/PHY.  Same
 * ChipIdea IP and register offsets as USB1; only the bases differ (OTG
 * 0x40430000 -> 0x4042C000, PHY 0x40434000 -> 0x40438000).  The host-mode
 * register names FRINDEX / PERIODICLISTBASE / ASYNCLISTADDR alias the very
 * offsets the device block calls DEVICEADDR / ENDPOINTLISTADDR.  IRQ = 135,
 * declared as IRQ_USB_OTG2 in core_pins.h (with an IRQ_USB2 alias there so
 * imxrt_usbhs.h's IRQ_USBHS resolves).  Bases + IRQ verified vs the qemu2
 * fsl-imxrt1170 model; offsets/bits vs CMSIS PERI_USB.h / PERI_USBPHY.h. */
#define USB_OTG2_BASE          0x4042C000u
#define USB2_GPTIMER0LD        (*(volatile uint32_t *)(USB_OTG2_BASE + 0x080))
#define USB2_GPTIMER0CTRL      (*(volatile uint32_t *)(USB_OTG2_BASE + 0x084))
#define USB2_GPTIMER1LD        (*(volatile uint32_t *)(USB_OTG2_BASE + 0x088))
#define USB2_GPTIMER1CTRL      (*(volatile uint32_t *)(USB_OTG2_BASE + 0x08C))
#define USB2_SBUSCFG           (*(volatile uint32_t *)(USB_OTG2_BASE + 0x090))
#define USB2_USBCMD            (*(volatile uint32_t *)(USB_OTG2_BASE + 0x140))
#define USB2_USBSTS            (*(volatile uint32_t *)(USB_OTG2_BASE + 0x144))
#define USB2_USBINTR           (*(volatile uint32_t *)(USB_OTG2_BASE + 0x148))
#define USB2_FRINDEX           (*(volatile uint32_t *)(USB_OTG2_BASE + 0x14C))
#define USB2_PERIODICLISTBASE  (*(volatile uint32_t *)(USB_OTG2_BASE + 0x154))
#define USB2_ASYNCLISTADDR     (*(volatile uint32_t *)(USB_OTG2_BASE + 0x158))
#define USB2_BURSTSIZE         (*(volatile uint32_t *)(USB_OTG2_BASE + 0x160))
#define USB2_PORTSC1           (*(volatile uint32_t *)(USB_OTG2_BASE + 0x184))
#define USB2_USBMODE           (*(volatile uint32_t *)(USB_OTG2_BASE + 0x1A8))

#define USBPHY2_BASE           0x40438000u
#define USBPHY2_PWD            (*(volatile uint32_t *)(USBPHY2_BASE + 0x00))
#define USBPHY2_CTRL           (*(volatile uint32_t *)(USBPHY2_BASE + 0x30))
#define USBPHY2_CTRL_SET       (*(volatile uint32_t *)(USBPHY2_BASE + 0x34))
#define USBPHY2_CTRL_CLR       (*(volatile uint32_t *)(USBPHY2_BASE + 0x38))
#define USBPHY2_PLL_SIC        (*(volatile uint32_t *)(USBPHY2_BASE + 0xA0))
#define USBPHY2_PLL_SIC_SET    (*(volatile uint32_t *)(USBPHY2_BASE + 0xA4))
#define USBPHY2_PLL_SIC_CLR    (*(volatile uint32_t *)(USBPHY2_BASE + 0xA8))

/* Extra generic USB_* bit masks referenced by imxrt_usbhs.h's host block but
 * not used by the device (USB1) side, hence absent from the device masks
 * above.  Standard EHCI / ChipIdea positions, each cross-checked against the
 * CMSIS PERI_USB.h *_MASK defines.  (RS / RST / PCE / UEE / TI0 / TI1 / PR /
 * HSP / USBMODE_CM and the GPTIMER RST/RUN masks already exist with the device
 * block; USBSTS UAI/UPI are inlined literally in imxrt_usbhs.h, not here.) */
/* USBCMD */
#define USB_USBCMD_FS_1(n)     (((n) & 0x3u) << 2)
#define USB_USBCMD_PSE         (1u << 4)
#define USB_USBCMD_ASE         (1u << 5)
#define USB_USBCMD_IAA         (1u << 6)
#define USB_USBCMD_ASP(n)      (((n) & 0x3u) << 8)
#define USB_USBCMD_ASPE        (1u << 11)
#define USB_USBCMD_FS_2        (1u << 15)
#define USB_USBCMD_ITC(n)      (((n) & 0xFFu) << 16)
/* USBSTS */
#define USB_USBSTS_SEI         (1u << 4)
#define USB_USBSTS_AAI         (1u << 5)
#define USB_USBSTS_HCH         (1u << 12)
#define USB_USBSTS_AS          (1u << 15)
#define USB_USBSTS_NAKI        (1u << 16)
/* USBINTR */
#define USB_USBINTR_SEE        (1u << 4)
#define USB_USBINTR_UAIE       (1u << 18)
#define USB_USBINTR_UPIE       (1u << 19)
#define USB_USBINTR_TIE1       (1u << 25)
/* PORTSC1 */
#define USB_PORTSC1_CCS        (1u << 0)
#define USB_PORTSC1_CSC        (1u << 1)
#define USB_PORTSC1_PE         (1u << 2)
#define USB_PORTSC1_PEC        (1u << 3)
#define USB_PORTSC1_OCC        (1u << 5)
#define USB_PORTSC1_FPR        (1u << 6)
#define USB_PORTSC1_PP         (1u << 12)
#define USB_PORTSC1_PFSC       (1u << 24)
'''.rstrip("\n")]
    L += ["",
          "/* --- SAI1 (I2S TX, Arduino audio) base 0x40404000, IRQ 76 --- */",
          "#define SAI1_TCSR (*(volatile uint32_t *)0x40404008u)",
          "#define SAI1_TCR1 (*(volatile uint32_t *)0x4040400Cu)",
          "#define SAI1_TCR2 (*(volatile uint32_t *)0x40404010u)",
          "#define SAI1_TCR3 (*(volatile uint32_t *)0x40404014u)",
          "#define SAI1_TCR4 (*(volatile uint32_t *)0x40404018u)",
          "#define SAI1_TCR5 (*(volatile uint32_t *)0x4040401Cu)",
          "#define SAI1_TDR0 (*(volatile uint32_t *)0x40404020u)",
          "#define SAI1_TFR0 (*(volatile uint32_t *)0x40404040u)",
          "#define SAI1_TMR  (*(volatile uint32_t *)0x40404060u)",
          "#define SAI_TCSR_TE  (1u << 31)",
          "#define SAI_TCSR_BCE (1u << 28)",
          "#define SAI_TCSR_FR  (1u << 25)",
          "#define SAI_TCSR_SR  (1u << 24)",
          "#define SAI_TCSR_FEF (1u << 18)",
          "#define SAI_TCSR_FWF (1u << 17)",
          "#define SAI_TCSR_FRF (1u << 16)",
          "#define SAI_TCSR_FRDE (1u << 0)",
          "#define SAI_TCR2_DIV(x)  ((uint32_t)(x) & 0xFFu)",
          "#define SAI_TCR2_BCD (1u << 24)",
          "#define SAI_TCR2_BCP (1u << 25)",
          "#define SAI_TCR2_MSEL(x) (((uint32_t)(x) & 0x3u) << 26)",
          "#define SAI_TCR3_TCE(x)  (((uint32_t)(x) & 0xFu) << 16)",
          "#define SAI_TCR4_FSD (1u << 0)",
          "#define SAI_TCR4_FSP (1u << 1)",
          "#define SAI_TCR4_FSE (1u << 3)",
          "#define SAI_TCR4_MF  (1u << 4)",
          "#define SAI_TCR4_SYWD(x) (((uint32_t)(x) & 0x1Fu) << 8)",
          "#define SAI_TCR4_FRSZ(x) (((uint32_t)(x) & 0x1Fu) << 16)",
          "#define SAI_TCR5_FBT(x)  (((uint32_t)(x) & 0x1Fu) << 8)",
          "#define SAI_TCR5_W0W(x)  (((uint32_t)(x) & 0x1Fu) << 16)",
          "#define SAI_TCR5_WNW(x)  (((uint32_t)(x) & 0x1Fu) << 24)",
          "/* SAI1 clock: root 64 (mux 4 = Audio PLL, div 16), LPCG 123 */",
          "#define CCM_CLOCK_ROOT64_CONTROL (*(volatile uint32_t *)0x40CC2000u)",
          "#define CCM_LPCG123_DIRECT       (*(volatile uint32_t *)0x40CC6F60u)",
          "/* SAI1 pins (ALT0, pad 0x02); TX are outputs, no select_input */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_17 (*(volatile uint32_t *)0x400E8150u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_21 (*(volatile uint32_t *)0x400E8160u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_22 (*(volatile uint32_t *)0x400E8164u)",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_23 (*(volatile uint32_t *)0x400E8168u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_17 (*(volatile uint32_t *)0x400E8394u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_21 (*(volatile uint32_t *)0x400E83A4u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_22 (*(volatile uint32_t *)0x400E83A8u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_23 (*(volatile uint32_t *)0x400E83ACu)",
          "#define IOMUXC_GPR_GPR0 (*(volatile uint32_t *)0x400E4000u)",
          "#define IOMUXC_GPR_GPR0_SAI1_MCLK_DIR (1u << 8)",
          "/* --- SAI1 RX (receive): registers mirror TX; bit positions identical --- */",
          "#define SAI1_RCSR (*(volatile uint32_t *)0x40404088u)",
          "#define SAI1_RCR1 (*(volatile uint32_t *)0x4040408Cu)",
          "#define SAI1_RCR2 (*(volatile uint32_t *)0x40404090u)",
          "#define SAI1_RCR3 (*(volatile uint32_t *)0x40404094u)",
          "#define SAI1_RCR4 (*(volatile uint32_t *)0x40404098u)",
          "#define SAI1_RCR5 (*(volatile uint32_t *)0x4040409Cu)",
          "#define SAI1_RDR0 (*(volatile uint32_t *)0x404040A0u)",
          "#define SAI1_RFR0 (*(volatile uint32_t *)0x404040C0u)",
          "#define SAI1_RMR  (*(volatile uint32_t *)0x404040E0u)",
          "#define SAI_RCSR_RE   (1u << 31)",
          "#define SAI_RCSR_BCE  (1u << 28)",
          "#define SAI_RCSR_FR   (1u << 25)",
          "#define SAI_RCSR_SR   (1u << 24)",
          "#define SAI_RCSR_FEF  (1u << 18)",
          "#define SAI_RCSR_FWF  (1u << 17)",
          "#define SAI_RCSR_FRF  (1u << 16)",
          "#define SAI_RCSR_FRDE (1u << 0)",
          "#define SAI_RCR2_SYNC(x) (((uint32_t)(x) & 0x3u) << 30)",
          "#define SAI_RCR3_RCE(x)  (((uint32_t)(x) & 0xFu) << 16)",
          "#define SAI_RCR4_FSP (1u << 1)",
          "#define SAI_RCR4_FSE (1u << 3)",
          "#define SAI_RCR4_MF  (1u << 4)",
          "#define SAI_RCR4_SYWD(x) (((uint32_t)(x) & 0x1Fu) << 8)",
          "#define SAI_RCR4_FRSZ(x) (((uint32_t)(x) & 0x1Fu) << 16)",
          "#define SAI_RCR5_FBT(x)  (((uint32_t)(x) & 0x1Fu) << 8)",
          "#define SAI_RCR5_W0W(x)  (((uint32_t)(x) & 0x1Fu) << 16)",
          "#define SAI_RCR5_WNW(x)  (((uint32_t)(x) & 0x1Fu) << 24)",
          "/* SAI1_RXD[0] = GPIO_AD_20 (ALT0); RX data is an input -> needs select_input */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_20 (*(volatile uint32_t *)0x400E815Cu)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_20 (*(volatile uint32_t *)0x400E83A0u)",
          "#define IOMUXC_SAI1_RX_DATA0_SELECT_INPUT (*(volatile uint32_t *)0x400E8674u)"]
    L += ["",
          "/* --- Audio PLL via ANATOP AI indirect interface (base 0x40C84000) --- */",
          "#define ANADIG_PLL_AUDIO_CTRL (*(volatile uint32_t *)0x40C84300u)",
          "#define ANADIG_PLL_AUDIO_CTRL_ENABLE_CLK (1u << 13)",
          "#define ANADIG_PLL_AUDIO_CTRL_GATE       (1u << 14)",
          "#define ANADIG_PLL_AUDIO_CTRL_STABLE     (1u << 29)",
          "#define ANADIG_MISC_AI_CTRL_AUDIO  (*(volatile uint32_t *)0x40C84880u)",
          "#define ANADIG_MISC_AI_WDATA_AUDIO (*(volatile uint32_t *)0x40C84890u)",
          "#define ANADIG_MISC_AI_RDATA_AUDIO (*(volatile uint32_t *)0x40C848A0u)",
          "#define ANADIG_AI_TOGGLE      (1u << 8)",
          "#define ANADIG_AI_TOGGLE_DONE (1u << 9)",
          "#define ANADIG_AI_RWB         (1u << 16)"]
    L += ["",
          "/* --- LPI2C5 (codec bus, LPSR domain) base 0x40C34000, IRQ 36 --- */",
          "#define LPI2C5_MCR    (*(volatile uint32_t *)0x40C34010u)",
          "#define LPI2C5_MSR    (*(volatile uint32_t *)0x40C34014u)",
          "#define LPI2C5_MIER   (*(volatile uint32_t *)0x40C34018u)",
          "#define LPI2C5_MCFGR1 (*(volatile uint32_t *)0x40C34024u)",
          "#define LPI2C5_MCCR0  (*(volatile uint32_t *)0x40C34048u)",
          "#define LPI2C5_MFCR   (*(volatile uint32_t *)0x40C34058u)",
          "#define LPI2C5_MTDR   (*(volatile uint32_t *)0x40C34060u)",
          "#define LPI2C5_MRDR   (*(volatile uint32_t *)0x40C34070u)",
          "#define LPI2C5_SCR    (*(volatile uint32_t *)0x40C34110u)",
          "#define LPI2C5_SSR    (*(volatile uint32_t *)0x40C34114u)",
          "#define LPI2C5_SIER   (*(volatile uint32_t *)0x40C34118u)",
          "#define LPI2C5_SCFGR1 (*(volatile uint32_t *)0x40C34124u)",
          "#define LPI2C5_SCFGR2 (*(volatile uint32_t *)0x40C34128u)",
          "#define LPI2C5_SAMR   (*(volatile uint32_t *)0x40C34140u)",
          "#define LPI2C5_SASR   (*(volatile uint32_t *)0x40C34150u)",
          "#define LPI2C5_STAR   (*(volatile uint32_t *)0x40C34154u)",
          "#define LPI2C5_STDR   (*(volatile uint32_t *)0x40C34160u)",
          "#define LPI2C5_SRDR   (*(volatile uint32_t *)0x40C34170u)",
          "/* LPI2C5 clock: root 41 (mux 1), LPCG 102 */",
          "#define CCM_CLOCK_ROOT41_CONTROL (*(volatile uint32_t *)0x40CC1480u)",
          "#define CCM_LPCG102_DIRECT       (*(volatile uint32_t *)0x40CC6CC0u)",
          "/* LPI2C5 pins (LPSR IOMUXC 0x40C08000): SCL=LPSR_05, SDA=LPSR_04.",
          " * The LPSR_04/05 mux+pad macros ALREADY exist in the digital-pin block,",
          " * so only the two SELECT_INPUT (daisy) registers are added here. */",
          "#define IOMUXC_LPI2C5_SCL_SELECT_INPUT (*(volatile uint32_t *)0x40C08084u)",
          "#define IOMUXC_LPI2C5_SDA_SELECT_INPUT (*(volatile uint32_t *)0x40C08088u)"]
    L += ['''
/* ---- eDMA + DMAMUX (classic Freescale eDMA: 32 channels, 16 IRQs) ----------
 * RT1176 uses the SAME IP as RT1062 (Teensy 4), relocated: eDMA 0x40070000,
 * DMAMUX 0x40074000.  cores/teensy4/DMAChannel.{h,cpp} ports with only base
 * retargets.  DMAMUX source numbers are RT1176-specific (NOT the RT1062 values;
 * verified against NXP PERI_DMAMUX.h and QEMU).  TCD0 at 0x40071000, stride 0x20.
 * Channel completion IRQs are NVIC 0..15 (channel n and n+16 share vector n);
 * DMA error is NVIC 16. */
/* eDMA control/status (base 0x40070000) */
#define DMA_CR       (*(volatile uint32_t *)0x40070000u)
#define DMA_ES       (*(volatile uint32_t *)0x40070004u)
#define DMA_ERQ      (*(volatile uint32_t *)0x4007000Cu)
#define DMA_EEI      (*(volatile uint32_t *)0x40070014u)
#define DMA_CEEI     (*(volatile uint8_t  *)0x40070018u)
#define DMA_SEEI     (*(volatile uint8_t  *)0x40070019u)
#define DMA_CERQ     (*(volatile uint8_t  *)0x4007001Au)
#define DMA_SERQ     (*(volatile uint8_t  *)0x4007001Bu)
#define DMA_CDNE     (*(volatile uint8_t  *)0x4007001Cu)
#define DMA_SSRT     (*(volatile uint8_t  *)0x4007001Du)
#define DMA_CERR     (*(volatile uint8_t  *)0x4007001Eu)
#define DMA_CINT     (*(volatile uint8_t  *)0x4007001Fu)
#define DMA_INT      (*(volatile uint32_t *)0x40070024u)
#define DMA_ERR      (*(volatile uint32_t *)0x4007002Cu)
#define DMA_HRS      (*(volatile uint32_t *)0x40070034u)
#define DMA_DCHPRI3  (*(volatile uint8_t  *)0x40070100u)   /* byte-swizzled priority array base */
/* DMA_CR bits */
#define DMA_CR_GRP1PRI ((uint32_t)(1<<10))
#define DMA_CR_EMLM    ((uint32_t)(1<<7))
#define DMA_CR_EDBG    ((uint32_t)(1<<1))
/* DMA_DCHPRIn bits */
#define DMA_DCHPRI_ECP ((uint8_t)(1<<7))
#define DMA_DCHPRI_DPA ((uint8_t)(1<<6))
/* TCD CSR bits */
#define DMA_TCD_CSR_DONE                 0x0080
#define DMA_TCD_CSR_MAJORELINK           0x0020
#define DMA_TCD_CSR_ESG                  0x0010
#define DMA_TCD_CSR_DREQ                 0x0008
#define DMA_TCD_CSR_INTHALF              0x0004
#define DMA_TCD_CSR_INTMAJOR             0x0002
#define DMA_TCD_CSR_START                0x0001
#define DMA_TCD_CSR_MAJORLINKCH(n)       (((n) & 0x1F) << 8)
#define DMA_TCD_CSR_MAJORLINKCH_MASK     0x1F00
/* TCD BITER linking bits */
#define DMA_TCD_BITER_ELINK                 ((uint16_t)1<<15)
#define DMA_TCD_BITER_ELINKYES_ELINK        0x8000
#define DMA_TCD_BITER_ELINKYES_LINKCH(n)    (((n) & 0x1F) << 9)
#define DMA_TCD_BITER_ELINKYES_LINKCH_MASK  0x3E00
/* DMAMUX (base 0x40074000): CHCFG0..31, 4 bytes apart */
#define DMAMUX_CHCFG0      (*(volatile uint32_t *)0x40074000u)
#define DMAMUX_CHCFG_ENBL  ((uint32_t)(1<<31))
#define DMAMUX_CHCFG_TRIG  ((uint32_t)(1<<30))
#define DMAMUX_CHCFG_A_ON  ((uint32_t)(1<<29))
/* eDMA clock gate: CCM LPCG22 (kCLOCK_Edma=22 -> 0x40CC6000 + 22*0x20). */
#define CCM_LPCG22_DIRECT  (*(volatile uint32_t *)0x40CC62C0u)
/* DMAMUX request sources (RT1176 silicon; NXP PERI_DMAMUX.h; matches QEMU wiring) */
#define DMAMUX_SOURCE_LPUART1_TX 8
#define DMAMUX_SOURCE_LPUART1_RX 9
#define DMAMUX_SOURCE_LPSPI1_RX  36
#define DMAMUX_SOURCE_LPSPI1_TX  37
#define DMAMUX_SOURCE_LPI2C1     48
#define DMAMUX_SOURCE_SAI1_RX    54
#define DMAMUX_SOURCE_SAI1_TX    55
'''.rstrip("\n")]
    L += ['''
/* FlexSPI1 IP-command registers (for the flash-emulated EEPROM program/erase
 * primitives in cores/imxrt1176/eeprom.c).  Same IP + offsets as the RT1062
 * FlexSPI in cores/teensy4/imxrt.h, retargeted to FlexSPI1 base 0x400CC000. */
#define FLEXSPI_MCR0     (*(volatile uint32_t *)(FLEXSPI_BASE + 0x000))
#define FLEXSPI_MCR0_SWRESET     ((uint32_t)(1<<0))
#define FLEXSPI_INTR     (*(volatile uint32_t *)(FLEXSPI_BASE + 0x014))
#define FLEXSPI_INTR_IPCMDDONE   ((uint32_t)(1<<0))
#define FLEXSPI_INTR_IPTXWE      ((uint32_t)(1<<6))
#define FLEXSPI_LUTKEY   (*(volatile uint32_t *)(FLEXSPI_BASE + 0x018))
#define FLEXSPI_LUTKEY_VALUE     ((uint32_t)0x5AF05AF0)
#define FLEXSPI_LUTCR    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x01C))
#define FLEXSPI_LUTCR_UNLOCK     ((uint32_t)(1<<1))
#define FLEXSPI_IPCR0    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x0A0))
#define FLEXSPI_IPCR1    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x0A4))
#define FLEXSPI_IPCR1_ISEQID(n)  ((uint32_t)(((n) & 0x0F) << 16))
#define FLEXSPI_IPCR1_IDATSZ(n)  ((uint32_t)(((n) & 0xFFFF) << 0))
#define FLEXSPI_IPCMD    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x0B0))
#define FLEXSPI_IPCMD_TRG        ((uint32_t)(1<<0))
#define FLEXSPI_IPRXFCR  (*(volatile uint32_t *)(FLEXSPI_BASE + 0x0B8))
#define FLEXSPI_IPRXFCR_CLRIPRXF ((uint32_t)(1<<0))
#define FLEXSPI_IPTXFCR  (*(volatile uint32_t *)(FLEXSPI_BASE + 0x0BC))
#define FLEXSPI_IPTXFCR_CLRIPTXF ((uint32_t)(1<<0))
#define FLEXSPI_RFDR0    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x100))
#define FLEXSPI_TFDR0    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x180))
#define FLEXSPI_LUT60    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x2F0))
#define FLEXSPI_LUT61    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x2F4))
#define FLEXSPI_LUT62    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x2F8))
#define FLEXSPI_LUT63    (*(volatile uint32_t *)(FLEXSPI_BASE + 0x2FC))
#define FLEXSPI_LUT_INSTRUCTION(opcode, pads, operand) ((uint32_t)(\\
	(((opcode) & 0x3F) << 10) | (((pads) & 0x03) << 8) | ((operand) & 0xFF)))
#define FLEXSPI_LUT_OPCODE_CMD_SDR   0x01
#define FLEXSPI_LUT_OPCODE_RADDR_SDR 0x02
#define FLEXSPI_LUT_OPCODE_WRITE_SDR 0x08
#define FLEXSPI_LUT_OPCODE_READ_SDR  0x09
#define FLEXSPI_LUT_NUM_PADS_1       0x00
#define FLEXSPI_LUT_NUM_PADS_4       0x02
'''.rstrip("\n")]
    # ==== SEMC (SMART External Memory Controller): external SDRAM bring-up ====
    # Registers/bitfields ported VERBATIM from NXP PERI_SEMC.h (SEMC_Type struct +
    # *_MASK/_SHIFT/(x) accessors). Base 0x400D4000 (MIMXRT1176_cm7_COMMON.h). SDRAM
    # pads GPIO_EMC_B1_00..B1_41 + B2_00..B2_20 (63 pads, all ALT0, pad-ctl 0x08) from
    # the SDK evkbmimxrt1170 driver_examples/semc/sdram pin_mux.c. Clock root 4 =
    # SYS_PLL2_PFD1 (594 MHz) / 3 = 198 MHz; LPCG gate 33. Consumed by Task 2 SDRAM init.
    L += ["", "/* ==== SEMC (external SDRAM controller) @ CS0 0x80000000 ==== */",
          "#define SEMC_BASE 0x400D4000u"]
    SEMC_REGS = [
        ("MCR",0x00), ("IOCR",0x04), ("BMCR0",0x08), ("BMCR1",0x0C), ("BR0",0x10),
        ("BR1",0x14), ("BR2",0x18), ("BR3",0x1C), ("BR4",0x20), ("BR5",0x24), ("BR6",0x28),
        ("BR7",0x2C), ("BR8",0x30), ("INTEN",0x38), ("INTR",0x3C), ("SDRAMCR0",0x40),
        ("SDRAMCR1",0x44), ("SDRAMCR2",0x48), ("SDRAMCR3",0x4C), ("DBICR0",0x80),
        ("DBICR1",0x84), ("IPCR0",0x90), ("IPCR1",0x94), ("IPCR2",0x98), ("IPCMD",0x9C),
        ("IPTXDAT",0xA0), ("IPRXDAT",0xB0), ("STS0",0xC0), ("STS1",0xC4), ("STS2",0xC8),
        ("STS3",0xCC), ("STS4",0xD0), ("STS5",0xD4), ("STS6",0xD8), ("STS7",0xDC),
        ("STS8",0xE0), ("STS9",0xE4), ("STS10",0xE8), ("STS11",0xEC), ("STS12",0xF0),
        ("DCCR",0x150),
    ]
    for _r,_o in SEMC_REGS:
        L.append(f"#define SEMC_{_r} (*(volatile uint32_t *)(SEMC_BASE + 0x{_o:02X}u))")
    L.append("#define SEMC_BR(n) (*(volatile uint32_t *)(SEMC_BASE + 0x10u + ((n) << 2)))  /* BR[0..8] */")
    L += ["", "/* SEMC register bitfields (verbatim from NXP PERI_SEMC.h) */"]
    L += """#define SEMC_MCR_SWRST_MASK (0x1U)
#define SEMC_MCR_SWRST_SHIFT (0U)
#define SEMC_MCR_SWRST(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_SWRST_SHIFT)) & SEMC_MCR_SWRST_MASK)
#define SEMC_MCR_MDIS_MASK (0x2U)
#define SEMC_MCR_MDIS_SHIFT (1U)
#define SEMC_MCR_MDIS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_MDIS_SHIFT)) & SEMC_MCR_MDIS_MASK)
#define SEMC_MCR_DQSMD_MASK (0x4U)
#define SEMC_MCR_DQSMD_SHIFT (2U)
#define SEMC_MCR_DQSMD(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_DQSMD_SHIFT)) & SEMC_MCR_DQSMD_MASK)
#define SEMC_MCR_WPOL0_MASK (0x40U)
#define SEMC_MCR_WPOL0_SHIFT (6U)
#define SEMC_MCR_WPOL0(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_WPOL0_SHIFT)) & SEMC_MCR_WPOL0_MASK)
#define SEMC_MCR_WPOL1_MASK (0x80U)
#define SEMC_MCR_WPOL1_SHIFT (7U)
#define SEMC_MCR_WPOL1(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_WPOL1_SHIFT)) & SEMC_MCR_WPOL1_MASK)
#define SEMC_MCR_CTO_MASK (0xFF0000U)
#define SEMC_MCR_CTO_SHIFT (16U)
#define SEMC_MCR_CTO(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_CTO_SHIFT)) & SEMC_MCR_CTO_MASK)
#define SEMC_MCR_BTO_MASK (0x1F000000U)
#define SEMC_MCR_BTO_SHIFT (24U)
#define SEMC_MCR_BTO(x) (((uint32_t)(((uint32_t)(x)) << SEMC_MCR_BTO_SHIFT)) & SEMC_MCR_BTO_MASK)
#define SEMC_IOCR_MUX_A8_MASK (0xFU)
#define SEMC_IOCR_MUX_A8_SHIFT (0U)
#define SEMC_IOCR_MUX_A8(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_A8_SHIFT)) & SEMC_IOCR_MUX_A8_MASK)
#define SEMC_IOCR_MUX_CSX0_MASK (0xF0U)
#define SEMC_IOCR_MUX_CSX0_SHIFT (4U)
#define SEMC_IOCR_MUX_CSX0(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CSX0_SHIFT)) & SEMC_IOCR_MUX_CSX0_MASK)
#define SEMC_IOCR_MUX_CSX1_MASK (0xF00U)
#define SEMC_IOCR_MUX_CSX1_SHIFT (8U)
#define SEMC_IOCR_MUX_CSX1(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CSX1_SHIFT)) & SEMC_IOCR_MUX_CSX1_MASK)
#define SEMC_IOCR_MUX_CSX2_MASK (0xF000U)
#define SEMC_IOCR_MUX_CSX2_SHIFT (12U)
#define SEMC_IOCR_MUX_CSX2(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CSX2_SHIFT)) & SEMC_IOCR_MUX_CSX2_MASK)
#define SEMC_IOCR_MUX_CSX3_MASK (0xF0000U)
#define SEMC_IOCR_MUX_CSX3_SHIFT (16U)
#define SEMC_IOCR_MUX_CSX3(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CSX3_SHIFT)) & SEMC_IOCR_MUX_CSX3_MASK)
#define SEMC_IOCR_MUX_RDY_MASK (0xF00000U)
#define SEMC_IOCR_MUX_RDY_SHIFT (20U)
#define SEMC_IOCR_MUX_RDY(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_RDY_SHIFT)) & SEMC_IOCR_MUX_RDY_MASK)
#define SEMC_IOCR_MUX_CLKX0_MASK (0x3000000U)
#define SEMC_IOCR_MUX_CLKX0_SHIFT (24U)
#define SEMC_IOCR_MUX_CLKX0(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CLKX0_SHIFT)) & SEMC_IOCR_MUX_CLKX0_MASK)
#define SEMC_IOCR_MUX_CLKX1_MASK (0xC000000U)
#define SEMC_IOCR_MUX_CLKX1_SHIFT (26U)
#define SEMC_IOCR_MUX_CLKX1(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_MUX_CLKX1_SHIFT)) & SEMC_IOCR_MUX_CLKX1_MASK)
#define SEMC_IOCR_CLKX0_AO_MASK (0x10000000U)
#define SEMC_IOCR_CLKX0_AO_SHIFT (28U)
#define SEMC_IOCR_CLKX0_AO(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_CLKX0_AO_SHIFT)) & SEMC_IOCR_CLKX0_AO_MASK)
#define SEMC_IOCR_CLKX1_AO_MASK (0x20000000U)
#define SEMC_IOCR_CLKX1_AO_SHIFT (29U)
#define SEMC_IOCR_CLKX1_AO(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IOCR_CLKX1_AO_SHIFT)) & SEMC_IOCR_CLKX1_AO_MASK)
#define SEMC_BMCR0_WQOS_MASK (0xFU)
#define SEMC_BMCR0_WQOS_SHIFT (0U)
#define SEMC_BMCR0_WQOS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR0_WQOS_SHIFT)) & SEMC_BMCR0_WQOS_MASK)
#define SEMC_BMCR0_WAGE_MASK (0xF0U)
#define SEMC_BMCR0_WAGE_SHIFT (4U)
#define SEMC_BMCR0_WAGE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR0_WAGE_SHIFT)) & SEMC_BMCR0_WAGE_MASK)
#define SEMC_BMCR0_WSH_MASK (0xFF00U)
#define SEMC_BMCR0_WSH_SHIFT (8U)
#define SEMC_BMCR0_WSH(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR0_WSH_SHIFT)) & SEMC_BMCR0_WSH_MASK)
#define SEMC_BMCR0_WRWS_MASK (0xFF0000U)
#define SEMC_BMCR0_WRWS_SHIFT (16U)
#define SEMC_BMCR0_WRWS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR0_WRWS_SHIFT)) & SEMC_BMCR0_WRWS_MASK)
#define SEMC_BMCR1_WQOS_MASK (0xFU)
#define SEMC_BMCR1_WQOS_SHIFT (0U)
#define SEMC_BMCR1_WQOS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR1_WQOS_SHIFT)) & SEMC_BMCR1_WQOS_MASK)
#define SEMC_BMCR1_WAGE_MASK (0xF0U)
#define SEMC_BMCR1_WAGE_SHIFT (4U)
#define SEMC_BMCR1_WAGE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR1_WAGE_SHIFT)) & SEMC_BMCR1_WAGE_MASK)
#define SEMC_BMCR1_WPH_MASK (0xFF00U)
#define SEMC_BMCR1_WPH_SHIFT (8U)
#define SEMC_BMCR1_WPH(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR1_WPH_SHIFT)) & SEMC_BMCR1_WPH_MASK)
#define SEMC_BMCR1_WRWS_MASK (0xFF0000U)
#define SEMC_BMCR1_WRWS_SHIFT (16U)
#define SEMC_BMCR1_WRWS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR1_WRWS_SHIFT)) & SEMC_BMCR1_WRWS_MASK)
#define SEMC_BMCR1_WBR_MASK (0xFF000000U)
#define SEMC_BMCR1_WBR_SHIFT (24U)
#define SEMC_BMCR1_WBR(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BMCR1_WBR_SHIFT)) & SEMC_BMCR1_WBR_MASK)
#define SEMC_BR_VLD_MASK (0x1U)
#define SEMC_BR_VLD_SHIFT (0U)
#define SEMC_BR_VLD(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BR_VLD_SHIFT)) & SEMC_BR_VLD_MASK)
#define SEMC_BR_MS_MASK (0x3EU)
#define SEMC_BR_MS_SHIFT (1U)
#define SEMC_BR_MS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BR_MS_SHIFT)) & SEMC_BR_MS_MASK)
#define SEMC_BR_BA_MASK (0xFFFFF000U)
#define SEMC_BR_BA_SHIFT (12U)
#define SEMC_BR_BA(x) (((uint32_t)(((uint32_t)(x)) << SEMC_BR_BA_SHIFT)) & SEMC_BR_BA_MASK)
#define SEMC_INTEN_IPCMDDONEEN_MASK (0x1U)
#define SEMC_INTEN_IPCMDDONEEN_SHIFT (0U)
#define SEMC_INTEN_IPCMDDONEEN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_IPCMDDONEEN_SHIFT)) & SEMC_INTEN_IPCMDDONEEN_MASK)
#define SEMC_INTEN_IPCMDERREN_MASK (0x2U)
#define SEMC_INTEN_IPCMDERREN_SHIFT (1U)
#define SEMC_INTEN_IPCMDERREN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_IPCMDERREN_SHIFT)) & SEMC_INTEN_IPCMDERREN_MASK)
#define SEMC_INTEN_AXICMDERREN_MASK (0x4U)
#define SEMC_INTEN_AXICMDERREN_SHIFT (2U)
#define SEMC_INTEN_AXICMDERREN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_AXICMDERREN_SHIFT)) & SEMC_INTEN_AXICMDERREN_MASK)
#define SEMC_INTEN_AXIBUSERREN_MASK (0x8U)
#define SEMC_INTEN_AXIBUSERREN_SHIFT (3U)
#define SEMC_INTEN_AXIBUSERREN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_AXIBUSERREN_SHIFT)) & SEMC_INTEN_AXIBUSERREN_MASK)
#define SEMC_INTEN_NDPAGEENDEN_MASK (0x10U)
#define SEMC_INTEN_NDPAGEENDEN_SHIFT (4U)
#define SEMC_INTEN_NDPAGEENDEN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_NDPAGEENDEN_SHIFT)) & SEMC_INTEN_NDPAGEENDEN_MASK)
#define SEMC_INTEN_NDNOPENDEN_MASK (0x20U)
#define SEMC_INTEN_NDNOPENDEN_SHIFT (5U)
#define SEMC_INTEN_NDNOPENDEN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTEN_NDNOPENDEN_SHIFT)) & SEMC_INTEN_NDNOPENDEN_MASK)
#define SEMC_INTR_IPCMDDONE_MASK (0x1U)
#define SEMC_INTR_IPCMDDONE_SHIFT (0U)
#define SEMC_INTR_IPCMDDONE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_IPCMDDONE_SHIFT)) & SEMC_INTR_IPCMDDONE_MASK)
#define SEMC_INTR_IPCMDERR_MASK (0x2U)
#define SEMC_INTR_IPCMDERR_SHIFT (1U)
#define SEMC_INTR_IPCMDERR(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_IPCMDERR_SHIFT)) & SEMC_INTR_IPCMDERR_MASK)
#define SEMC_INTR_AXICMDERR_MASK (0x4U)
#define SEMC_INTR_AXICMDERR_SHIFT (2U)
#define SEMC_INTR_AXICMDERR(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_AXICMDERR_SHIFT)) & SEMC_INTR_AXICMDERR_MASK)
#define SEMC_INTR_AXIBUSERR_MASK (0x8U)
#define SEMC_INTR_AXIBUSERR_SHIFT (3U)
#define SEMC_INTR_AXIBUSERR(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_AXIBUSERR_SHIFT)) & SEMC_INTR_AXIBUSERR_MASK)
#define SEMC_INTR_NDPAGEEND_MASK (0x10U)
#define SEMC_INTR_NDPAGEEND_SHIFT (4U)
#define SEMC_INTR_NDPAGEEND(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_NDPAGEEND_SHIFT)) & SEMC_INTR_NDPAGEEND_MASK)
#define SEMC_INTR_NDNOPEND_MASK (0x20U)
#define SEMC_INTR_NDNOPEND_SHIFT (5U)
#define SEMC_INTR_NDNOPEND(x) (((uint32_t)(((uint32_t)(x)) << SEMC_INTR_NDNOPEND_SHIFT)) & SEMC_INTR_NDNOPEND_MASK)
#define SEMC_SDRAMCR0_PS_MASK (0x3U)
#define SEMC_SDRAMCR0_PS_SHIFT (0U)
#define SEMC_SDRAMCR0_PS(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_PS_SHIFT)) & SEMC_SDRAMCR0_PS_MASK)
#define SEMC_SDRAMCR0_BL_MASK (0x70U)
#define SEMC_SDRAMCR0_BL_SHIFT (4U)
#define SEMC_SDRAMCR0_BL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_BL_SHIFT)) & SEMC_SDRAMCR0_BL_MASK)
#define SEMC_SDRAMCR0_COL8_MASK (0x80U)
#define SEMC_SDRAMCR0_COL8_SHIFT (7U)
#define SEMC_SDRAMCR0_COL8(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_COL8_SHIFT)) & SEMC_SDRAMCR0_COL8_MASK)
#define SEMC_SDRAMCR0_COL_MASK (0x300U)
#define SEMC_SDRAMCR0_COL_SHIFT (8U)
#define SEMC_SDRAMCR0_COL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_COL_SHIFT)) & SEMC_SDRAMCR0_COL_MASK)
#define SEMC_SDRAMCR0_CL_MASK (0xC00U)
#define SEMC_SDRAMCR0_CL_SHIFT (10U)
#define SEMC_SDRAMCR0_CL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_CL_SHIFT)) & SEMC_SDRAMCR0_CL_MASK)
#define SEMC_SDRAMCR0_BANK2_MASK (0x4000U)
#define SEMC_SDRAMCR0_BANK2_SHIFT (14U)
#define SEMC_SDRAMCR0_BANK2(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR0_BANK2_SHIFT)) & SEMC_SDRAMCR0_BANK2_MASK)
#define SEMC_SDRAMCR1_PRE2ACT_MASK (0xFU)
#define SEMC_SDRAMCR1_PRE2ACT_SHIFT (0U)
#define SEMC_SDRAMCR1_PRE2ACT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_PRE2ACT_SHIFT)) & SEMC_SDRAMCR1_PRE2ACT_MASK)
#define SEMC_SDRAMCR1_ACT2RW_MASK (0xF0U)
#define SEMC_SDRAMCR1_ACT2RW_SHIFT (4U)
#define SEMC_SDRAMCR1_ACT2RW(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_ACT2RW_SHIFT)) & SEMC_SDRAMCR1_ACT2RW_MASK)
#define SEMC_SDRAMCR1_RFRC_MASK (0x1F00U)
#define SEMC_SDRAMCR1_RFRC_SHIFT (8U)
#define SEMC_SDRAMCR1_RFRC(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_RFRC_SHIFT)) & SEMC_SDRAMCR1_RFRC_MASK)
#define SEMC_SDRAMCR1_WRC_MASK (0xE000U)
#define SEMC_SDRAMCR1_WRC_SHIFT (13U)
#define SEMC_SDRAMCR1_WRC(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_WRC_SHIFT)) & SEMC_SDRAMCR1_WRC_MASK)
#define SEMC_SDRAMCR1_CKEOFF_MASK (0xF0000U)
#define SEMC_SDRAMCR1_CKEOFF_SHIFT (16U)
#define SEMC_SDRAMCR1_CKEOFF(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_CKEOFF_SHIFT)) & SEMC_SDRAMCR1_CKEOFF_MASK)
#define SEMC_SDRAMCR1_ACT2PRE_MASK (0xF00000U)
#define SEMC_SDRAMCR1_ACT2PRE_SHIFT (20U)
#define SEMC_SDRAMCR1_ACT2PRE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR1_ACT2PRE_SHIFT)) & SEMC_SDRAMCR1_ACT2PRE_MASK)
#define SEMC_SDRAMCR2_SRRC_MASK (0xFFU)
#define SEMC_SDRAMCR2_SRRC_SHIFT (0U)
#define SEMC_SDRAMCR2_SRRC(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR2_SRRC_SHIFT)) & SEMC_SDRAMCR2_SRRC_MASK)
#define SEMC_SDRAMCR2_REF2REF_MASK (0xFF00U)
#define SEMC_SDRAMCR2_REF2REF_SHIFT (8U)
#define SEMC_SDRAMCR2_REF2REF(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR2_REF2REF_SHIFT)) & SEMC_SDRAMCR2_REF2REF_MASK)
#define SEMC_SDRAMCR2_ACT2ACT_MASK (0xFF0000U)
#define SEMC_SDRAMCR2_ACT2ACT_SHIFT (16U)
#define SEMC_SDRAMCR2_ACT2ACT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR2_ACT2ACT_SHIFT)) & SEMC_SDRAMCR2_ACT2ACT_MASK)
#define SEMC_SDRAMCR2_ITO_MASK (0xFF000000U)
#define SEMC_SDRAMCR2_ITO_SHIFT (24U)
#define SEMC_SDRAMCR2_ITO(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR2_ITO_SHIFT)) & SEMC_SDRAMCR2_ITO_MASK)
#define SEMC_SDRAMCR3_REN_MASK (0x1U)
#define SEMC_SDRAMCR3_REN_SHIFT (0U)
#define SEMC_SDRAMCR3_REN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR3_REN_SHIFT)) & SEMC_SDRAMCR3_REN_MASK)
#define SEMC_SDRAMCR3_REBL_MASK (0xEU)
#define SEMC_SDRAMCR3_REBL_SHIFT (1U)
#define SEMC_SDRAMCR3_REBL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR3_REBL_SHIFT)) & SEMC_SDRAMCR3_REBL_MASK)
#define SEMC_SDRAMCR3_PRESCALE_MASK (0xFF00U)
#define SEMC_SDRAMCR3_PRESCALE_SHIFT (8U)
#define SEMC_SDRAMCR3_PRESCALE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR3_PRESCALE_SHIFT)) & SEMC_SDRAMCR3_PRESCALE_MASK)
#define SEMC_SDRAMCR3_RT_MASK (0xFF0000U)
#define SEMC_SDRAMCR3_RT_SHIFT (16U)
#define SEMC_SDRAMCR3_RT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR3_RT_SHIFT)) & SEMC_SDRAMCR3_RT_MASK)
#define SEMC_SDRAMCR3_UT_MASK (0xFF000000U)
#define SEMC_SDRAMCR3_UT_SHIFT (24U)
#define SEMC_SDRAMCR3_UT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_SDRAMCR3_UT_SHIFT)) & SEMC_SDRAMCR3_UT_MASK)
#define SEMC_IPCR0_SA_MASK (0xFFFFFFFFU)
#define SEMC_IPCR0_SA_SHIFT (0U)
#define SEMC_IPCR0_SA(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR0_SA_SHIFT)) & SEMC_IPCR0_SA_MASK)
#define SEMC_IPCR1_DATSZ_MASK (0x7U)
#define SEMC_IPCR1_DATSZ_SHIFT (0U)
#define SEMC_IPCR1_DATSZ(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR1_DATSZ_SHIFT)) & SEMC_IPCR1_DATSZ_MASK)
#define SEMC_IPCR1_NAND_EXT_ADDR_MASK (0xFF00U)
#define SEMC_IPCR1_NAND_EXT_ADDR_SHIFT (8U)
#define SEMC_IPCR1_NAND_EXT_ADDR(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR1_NAND_EXT_ADDR_SHIFT)) & SEMC_IPCR1_NAND_EXT_ADDR_MASK)
#define SEMC_IPCR2_BM0_MASK (0x1U)
#define SEMC_IPCR2_BM0_SHIFT (0U)
#define SEMC_IPCR2_BM0(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR2_BM0_SHIFT)) & SEMC_IPCR2_BM0_MASK)
#define SEMC_IPCR2_BM1_MASK (0x2U)
#define SEMC_IPCR2_BM1_SHIFT (1U)
#define SEMC_IPCR2_BM1(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR2_BM1_SHIFT)) & SEMC_IPCR2_BM1_MASK)
#define SEMC_IPCR2_BM2_MASK (0x4U)
#define SEMC_IPCR2_BM2_SHIFT (2U)
#define SEMC_IPCR2_BM2(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR2_BM2_SHIFT)) & SEMC_IPCR2_BM2_MASK)
#define SEMC_IPCR2_BM3_MASK (0x8U)
#define SEMC_IPCR2_BM3_SHIFT (3U)
#define SEMC_IPCR2_BM3(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCR2_BM3_SHIFT)) & SEMC_IPCR2_BM3_MASK)
#define SEMC_IPCMD_CMD_MASK (0xFFFFU)
#define SEMC_IPCMD_CMD_SHIFT (0U)
#define SEMC_IPCMD_CMD(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCMD_CMD_SHIFT)) & SEMC_IPCMD_CMD_MASK)
#define SEMC_IPCMD_KEY_MASK (0xFFFF0000U)
#define SEMC_IPCMD_KEY_SHIFT (16U)
#define SEMC_IPCMD_KEY(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPCMD_KEY_SHIFT)) & SEMC_IPCMD_KEY_MASK)
#define SEMC_IPTXDAT_DAT_MASK (0xFFFFFFFFU)
#define SEMC_IPTXDAT_DAT_SHIFT (0U)
#define SEMC_IPTXDAT_DAT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPTXDAT_DAT_SHIFT)) & SEMC_IPTXDAT_DAT_MASK)
#define SEMC_IPRXDAT_DAT_MASK (0xFFFFFFFFU)
#define SEMC_IPRXDAT_DAT_SHIFT (0U)
#define SEMC_IPRXDAT_DAT(x) (((uint32_t)(((uint32_t)(x)) << SEMC_IPRXDAT_DAT_SHIFT)) & SEMC_IPRXDAT_DAT_MASK)
#define SEMC_STS0_IDLE_MASK (0x1U)
#define SEMC_STS0_IDLE_SHIFT (0U)
#define SEMC_STS0_IDLE(x) (((uint32_t)(((uint32_t)(x)) << SEMC_STS0_IDLE_SHIFT)) & SEMC_STS0_IDLE_MASK)
#define SEMC_STS0_NARDY_MASK (0x2U)
#define SEMC_STS0_NARDY_SHIFT (1U)
#define SEMC_STS0_NARDY(x) (((uint32_t)(((uint32_t)(x)) << SEMC_STS0_NARDY_SHIFT)) & SEMC_STS0_NARDY_MASK)
#define SEMC_DCCR_SDRAMEN_MASK (0x1U)
#define SEMC_DCCR_SDRAMEN_SHIFT (0U)
#define SEMC_DCCR_SDRAMEN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SDRAMEN_SHIFT)) & SEMC_DCCR_SDRAMEN_MASK)
#define SEMC_DCCR_SDRAMVAL_MASK (0x3EU)
#define SEMC_DCCR_SDRAMVAL_SHIFT (1U)
#define SEMC_DCCR_SDRAMVAL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SDRAMVAL_SHIFT)) & SEMC_DCCR_SDRAMVAL_MASK)
#define SEMC_DCCR_NOREN_MASK (0x100U)
#define SEMC_DCCR_NOREN_SHIFT (8U)
#define SEMC_DCCR_NOREN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_NOREN_SHIFT)) & SEMC_DCCR_NOREN_MASK)
#define SEMC_DCCR_NORVAL_MASK (0x3E00U)
#define SEMC_DCCR_NORVAL_SHIFT (9U)
#define SEMC_DCCR_NORVAL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_NORVAL_SHIFT)) & SEMC_DCCR_NORVAL_MASK)
#define SEMC_DCCR_SRAM0EN_MASK (0x10000U)
#define SEMC_DCCR_SRAM0EN_SHIFT (16U)
#define SEMC_DCCR_SRAM0EN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SRAM0EN_SHIFT)) & SEMC_DCCR_SRAM0EN_MASK)
#define SEMC_DCCR_SRAM0VAL_MASK (0x3E0000U)
#define SEMC_DCCR_SRAM0VAL_SHIFT (17U)
#define SEMC_DCCR_SRAM0VAL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SRAM0VAL_SHIFT)) & SEMC_DCCR_SRAM0VAL_MASK)
#define SEMC_DCCR_SRAMXEN_MASK (0x1000000U)
#define SEMC_DCCR_SRAMXEN_SHIFT (24U)
#define SEMC_DCCR_SRAMXEN(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SRAMXEN_SHIFT)) & SEMC_DCCR_SRAMXEN_MASK)
#define SEMC_DCCR_SRAMXVAL_MASK (0x3E000000U)
#define SEMC_DCCR_SRAMXVAL_SHIFT (25U)
#define SEMC_DCCR_SRAMXVAL(x) (((uint32_t)(((uint32_t)(x)) << SEMC_DCCR_SRAMXVAL_SHIFT)) & SEMC_DCCR_SRAMXVAL_MASK)""".split("\n")
    L += ["",
          "/* SDRAM IP command codes (fsl_semc.h semc_ipcmd_sdram_t) + magic key */",
          "#define kSEMC_SDRAMCM_Read 0x8u",
          "#define kSEMC_SDRAMCM_Write 0x9u",
          "#define kSEMC_SDRAMCM_Modeset 0xAu",
          "#define kSEMC_SDRAMCM_Active 0xBu",
          "#define kSEMC_SDRAMCM_AutoRefresh 0xCu",
          "#define kSEMC_SDRAMCM_SelfRefresh 0xDu",
          "#define kSEMC_SDRAMCM_Precharge 0xEu",
          "#define kSEMC_SDRAMCM_Prechargeall 0xFu",
          "#define SEMC_IPCMD_KEY_MAGIC 0xA55Au  /* SEMC_IPCOMMANDMAGICKEY */",
          "#define SEMC_SDRAM_MODESETCAL_OFFSET 4u  /* mode = burstLen | (CL << 4) */"]
    L += ["",
          "/* SEMC SDRAM pads (SDK semc/sdram pin_mux.c): all IOMUXC MUX_MODE=ALT0,",
          " * pad-ctl 0x08 = PDRV high-drive + internal pulldown (incl. CLK/CLKX). */",
          "#define SEMC_PAD_MUX_ALT 0x0u",
          "#define SEMC_PAD_CTL_VAL 0x08u"]
    SEMC_PINS = [
        ("GPIO_EMC_B1_00","DATA00"), ("GPIO_EMC_B1_01","DATA01"), ("GPIO_EMC_B1_02","DATA02"),
        ("GPIO_EMC_B1_03","DATA03"), ("GPIO_EMC_B1_04","DATA04"), ("GPIO_EMC_B1_05","DATA05"),
        ("GPIO_EMC_B1_06","DATA06"), ("GPIO_EMC_B1_07","DATA07"), ("GPIO_EMC_B1_08","DM00"),
        ("GPIO_EMC_B1_09","ADDR00"), ("GPIO_EMC_B1_10","ADDR01"), ("GPIO_EMC_B1_11","ADDR02"),
        ("GPIO_EMC_B1_12","ADDR03"), ("GPIO_EMC_B1_13","ADDR04"), ("GPIO_EMC_B1_14","ADDR05"),
        ("GPIO_EMC_B1_15","ADDR06"), ("GPIO_EMC_B1_16","ADDR07"), ("GPIO_EMC_B1_17","ADDR08"),
        ("GPIO_EMC_B1_18","ADDR09"), ("GPIO_EMC_B1_19","ADDR11"), ("GPIO_EMC_B1_20","ADDR12"),
        ("GPIO_EMC_B1_21","BA0"), ("GPIO_EMC_B1_22","BA1"), ("GPIO_EMC_B1_23","ADDR10"),
        ("GPIO_EMC_B1_24","CAS"), ("GPIO_EMC_B1_25","RAS"), ("GPIO_EMC_B1_26","CLK"),
        ("GPIO_EMC_B1_27","CKE"), ("GPIO_EMC_B1_28","WE"), ("GPIO_EMC_B1_29","CS0"),
        ("GPIO_EMC_B1_30","DATA08"), ("GPIO_EMC_B1_31","DATA09"), ("GPIO_EMC_B1_32","DATA10"),
        ("GPIO_EMC_B1_33","DATA11"), ("GPIO_EMC_B1_34","DATA12"), ("GPIO_EMC_B1_35","DATA13"),
        ("GPIO_EMC_B1_36","DATA14"), ("GPIO_EMC_B1_37","DATA15"), ("GPIO_EMC_B1_38","DM01"),
        ("GPIO_EMC_B1_39","DQS"), ("GPIO_EMC_B1_40","RDY"), ("GPIO_EMC_B1_41","CSX00"),
        ("GPIO_EMC_B2_00","DATA16"), ("GPIO_EMC_B2_01","DATA17"), ("GPIO_EMC_B2_02","DATA18"),
        ("GPIO_EMC_B2_03","DATA19"), ("GPIO_EMC_B2_04","DATA20"), ("GPIO_EMC_B2_05","DATA21"),
        ("GPIO_EMC_B2_06","DATA22"), ("GPIO_EMC_B2_07","DATA23"), ("GPIO_EMC_B2_08","DM02"),
        ("GPIO_EMC_B2_09","DATA24"), ("GPIO_EMC_B2_10","DATA25"), ("GPIO_EMC_B2_11","DATA26"),
        ("GPIO_EMC_B2_12","DATA27"), ("GPIO_EMC_B2_13","DATA28"), ("GPIO_EMC_B2_14","DATA29"),
        ("GPIO_EMC_B2_15","DATA30"), ("GPIO_EMC_B2_16","DATA31"), ("GPIO_EMC_B2_17","DM03"),
        ("GPIO_EMC_B2_18","DQS4"), ("GPIO_EMC_B2_19","CLKX00"), ("GPIO_EMC_B2_20","CLKX01"),
    ]
    for _i,(_pad,_sig) in enumerate(SEMC_PINS):
        L.append(f"#define IOMUXC_SW_MUX_CTL_PAD_{_pad} (*(volatile uint32_t *)0x{0x400E8010+_i*4:08X}u) /* SEMC_{_sig} */")
    for _i,(_pad,_sig) in enumerate(SEMC_PINS):
        L.append(f"#define IOMUXC_SW_PAD_CTL_PAD_{_pad} (*(volatile uint32_t *)0x{0x400E8254+_i*4:08X}u) /* SEMC_{_sig} */")
    L += ["",
          "/* SEMC clock: root 4 (kCLOCK_Root_Semc) = SYS_PLL2_PFD1 594MHz / 3 = 198MHz;",
          " * gate LPCG33 (kCLOCK_Semc). semc_clock_hz = 198000000 for Task 2 timing. */",
          "#define CCM_CLOCK_ROOT4_CONTROL (*(volatile uint32_t *)0x40CC0200u) /* kCLOCK_Root_Semc */",
          "#define CCM_LPCG33_DIRECT       (*(volatile uint32_t *)0x40CC6420u) /* kCLOCK_Semc gate */",
          "#define SEMC_CLOCK_HZ 198000000u  /* SYS_PLL2_PFD1 (594 MHz) / 3 */"]
    L += ["",
          "/* External SDRAM attribute -> .externalram (imxrt1176.ld ERAM @ 0x80000000) */",
          "#ifndef EXTMEM",
          "#define EXTMEM __attribute__((section(\".externalram\"), used))",
          "#endif"]
    # ==== ENET 10/100 (Freescale FEC) register plumbing -- Task 1 ============
    # Base 0x40424000 + IRQn 137 confirmed in MIMXRT1176_cm7_COMMON.h (ENET_BASE
    # auto-emitted above via WANTED).  Register offsets + bitfields verified
    # against NXP RT1170/periph/PERI_ENET.h (ENET_Type struct + ENET_* masks) and
    # PERI_IOMUXC_GPR.h (GPR4/GPR28 struct offsets + field masks).  No driver
    # logic yet -- pure register/IRQ plumbing consumed by a later enet.c task.
    L += ["", "/* ==== ENET 10/100 (Freescale FEC) @ 0x40424000, IRQ 137 ==== */",
          "/* Register offsets verified against RT1170/periph/PERI_ENET.h */",
          "#define ENET_EIR   (*(volatile uint32_t *)(ENET_BASE + 0x004u))",
          "#define ENET_EIMR  (*(volatile uint32_t *)(ENET_BASE + 0x008u))",
          "#define ENET_RDAR  (*(volatile uint32_t *)(ENET_BASE + 0x010u))",
          "#define ENET_TDAR  (*(volatile uint32_t *)(ENET_BASE + 0x014u))",
          "#define ENET_ECR   (*(volatile uint32_t *)(ENET_BASE + 0x024u))",
          "#define ENET_MMFR  (*(volatile uint32_t *)(ENET_BASE + 0x040u))",
          "#define ENET_MSCR  (*(volatile uint32_t *)(ENET_BASE + 0x044u))",
          "#define ENET_MIBC  (*(volatile uint32_t *)(ENET_BASE + 0x064u))",
          "#define ENET_RCR   (*(volatile uint32_t *)(ENET_BASE + 0x084u))",
          "#define ENET_TCR   (*(volatile uint32_t *)(ENET_BASE + 0x0C4u))",
          "#define ENET_PALR  (*(volatile uint32_t *)(ENET_BASE + 0x0E4u))",
          "#define ENET_PAUR  (*(volatile uint32_t *)(ENET_BASE + 0x0E8u))",
          "#define ENET_OPD   (*(volatile uint32_t *)(ENET_BASE + 0x0ECu))",
          "#define ENET_TFWR  (*(volatile uint32_t *)(ENET_BASE + 0x144u))",
          "#define ENET_RDSR  (*(volatile uint32_t *)(ENET_BASE + 0x180u))",
          "#define ENET_TDSR  (*(volatile uint32_t *)(ENET_BASE + 0x184u))",
          "#define ENET_MRBR  (*(volatile uint32_t *)(ENET_BASE + 0x188u))",
          "#define ENET_TACC  (*(volatile uint32_t *)(ENET_BASE + 0x1C0u))",
          "#define ENET_RACC  (*(volatile uint32_t *)(ENET_BASE + 0x1C4u))",
          "/* ECR bits (verified: RESET=bit0, ETHEREN=bit1, EN1588=bit4, DBSWP=bit8) */",
          "#define ENET_ECR_RESET   (1u<<0)",
          "#define ENET_ECR_ETHEREN (1u<<1)",
          "#define ENET_ECR_EN1588  (1u<<4)",
          "#define ENET_ECR_DBSWP   (1u<<8)",
          "/* EIR/EIMR bits (verified: MII=bit23, RXF=bit25, TXF=bit27) */",
          "#define ENET_EIR_MII (1u<<23)",
          "#define ENET_EIR_RXF (1u<<25)",
          "#define ENET_EIR_TXF (1u<<27)",
          "/* RDAR/TDAR active bit (SDK names the field RDAR/TDAR; mask 0x1000000=bit24) */",
          "#define ENET_RDAR_ACTIVE (1u<<24)",
          "#define ENET_TDAR_ACTIVE (1u<<24)",
          "/* MSCR MII_SPEED field (verified mask 0x7E, shift 1 -> 6-bit field): MDC = ref/((MII_SPEED+1)*2) */",
          "#define ENET_MSCR_MII_SPEED(n) (((n)&0x3Fu)<<1)",
          "/* RCR bits (RT1176 RM / FNET fnet_fec.h; QEMU imx_fec.h): MII_MODE=bit2,",
          " * RMII_MODE=bit8, DRT(half-duplex)=bit1, FCE=bit5, MAX_FL=[29:16] (14-bit). */",
          "#define ENET_RCR_DRT       (1u<<1)",
          "#define ENET_RCR_MII_MODE  (1u<<2)",
          "#define ENET_RCR_FCE       (1u<<5)",
          "#define ENET_RCR_RMII_MODE (1u<<8)",
          "#define ENET_RCR_MAX_FL(n) (((n)&0x3FFFu)<<16)",
          "/* TCR bits: GTS=bit0, FDEN(full-duplex)=bit2 */",
          "#define ENET_TCR_GTS       (1u<<0)",
          "#define ENET_TCR_FDEN      (1u<<2)",
          "/* MMFR fields (clause-22; verified against ENET_MMFR_ST/OP/TA/PA/RA masks) */",
          "#define ENET_MMFR_ST_01   (1u<<30)",
          "#define ENET_MMFR_OP_READ (2u<<28)",
          "#define ENET_MMFR_OP_WRITE (1u<<28)",
          "#define ENET_MMFR_TA_10   (2u<<16)",
          "#define ENET_MMFR_PA(a)   (((a)&0x1Fu)<<23)",
          "#define ENET_MMFR_RA(r)   (((r)&0x1Fu)<<18)",
          "/* Legacy 8-byte buffer-descriptor status bits: these live in the BD memory",
          " * structure, not the MMIO register map, so PERI_ENET.h has no masks for",
          " * them -- standard Freescale/NXP FEC BD layout (same across i.MX RT/",
          " * Kinetis/Vybrid), per the RT1170 RM ENET chapter. */",
          "#define ENET_TXBD_R  (1u<<15)",
          "#define ENET_TXBD_TO1 (1u<<14)",
          "#define ENET_TXBD_W  (1u<<13)",
          "#define ENET_TXBD_TO2 (1u<<12)",
          "#define ENET_TXBD_L  (1u<<11)",
          "#define ENET_TXBD_TC (1u<<10)",
          "#define ENET_RXBD_E  (1u<<15)",
          "#define ENET_RXBD_W  (1u<<13)",
          "#define ENET_RXBD_L  (1u<<11)",
          "/* RX BD error/status bits (RM legacy RxBD; match FNET + QEMU imx_fec.h) */",
          "#define ENET_RXBD_M  (1u<<8)   /* MISS (promiscuous)          */",
          "#define ENET_RXBD_BC (1u<<7)   /* broadcast                   */",
          "#define ENET_RXBD_MC (1u<<6)   /* multicast                   */",
          "#define ENET_RXBD_LG (1u<<5)   /* frame length violation      */",
          "#define ENET_RXBD_NO (1u<<4)   /* non-octet aligned frame     */",
          "#define ENET_RXBD_CR (1u<<2)   /* CRC/frame error             */",
          "#define ENET_RXBD_OV (1u<<1)   /* FIFO overrun                */",
          "#define ENET_RXBD_TR (1u<<0)   /* frame truncated             */",
          "#define ENET_RXBD_ERR (ENET_RXBD_LG|ENET_RXBD_NO|ENET_RXBD_CR|ENET_RXBD_OV|ENET_RXBD_TR)",
          "/* IOMUXC_GPR ENET fields.  GPR4 offset 0x10, GPR28 offset 0x70 (both",
          " * verified against the PERI_IOMUXC_GPR.h IOMUXC_GPR_Type struct); absolute-",
          " * address style matches the existing GPR0/14/16/17/18 defines above (this",
          " * codebase does not route GPR regs through IOMUXC_GPR_BASE even though that",
          " * macro exists).  Neither GPR4 nor GPR28 was previously defined. */",
          "#define IOMUXC_GPR_GPR4  (*(volatile uint32_t *)0x400E4010u)",
          "#define IOMUXC_GPR_GPR4_ENET_REF_CLK_DIR (1u<<1)",
          "#define IOMUXC_GPR_GPR28 (*(volatile uint32_t *)0x400E4070u)",
          "#define IOMUXC_GPR_GPR28_CACHE_ENET (1u<<7)",
          "/* ENET clock: root 51 = kCLOCK_Root_Enet1, LPCG gate 112 = kCLOCK_Enet",
          " * (both confirmed in fsl_clock.h clock_root_t/clock_lpcg_t).  mux=4",
          " * (SysPll1Div2), div=10 -> 50 MHz matches the SDK enet/txrx_transfer",
          " * BOARD_InitModuleClock {.mux=4,.div=10}.  Root/LPCG addresses follow the",
          " * generator's own CCM strides (ROOT n @ 0x40CC0000 + n*0x80; LPCG n DIRECT",
          " * @ 0x40CC6000 + n*0x20), cross-checked vs ROOT58/LPCG117 above. */",
          "#define CCM_CLOCK_ROOT51_CONTROL (*(volatile uint32_t *)0x40CC1980u)",
          "#define CCM_LPCG112_DIRECT       (*(volatile uint32_t *)0x40CC6E00u)",
          "/* ENET RMII + MDIO + PHY-reset pads (Task 3) -- verified vs fsl_iomuxc.h.",
          " * DISP_B2/AD pads in the main IOMUXC block @ 0x400E8000; LPSR_12 in the",
          " * LPSR block @ 0x40C08000.  ENET_*_SELECT_INPUT daisy regs are one-offs,",
          " * written to literal addresses directly in enet.c (not emitted here). */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_32       (*(volatile uint32_t *)0x400E818Cu) /* ENET_MDC   ALT3 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_33       (*(volatile uint32_t *)0x400E8190u) /* ENET_MDIO  ALT3 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_02  (*(volatile uint32_t *)0x400E821Cu) /* ENET_TX_DATA00 ALT1 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_03  (*(volatile uint32_t *)0x400E8220u) /* ENET_TX_DATA01 ALT1 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_04  (*(volatile uint32_t *)0x400E8224u) /* ENET_TX_EN     ALT1 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_05  (*(volatile uint32_t *)0x400E8228u) /* ENET_REF_CLK   ALT2 (SION) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_06  (*(volatile uint32_t *)0x400E822Cu) /* ENET_RX_DATA00 ALT1 (SION) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_07  (*(volatile uint32_t *)0x400E8230u) /* ENET_RX_DATA01 ALT1 (SION) */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_08  (*(volatile uint32_t *)0x400E8234u) /* ENET_RX_EN     ALT1 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_DISP_B2_09  (*(volatile uint32_t *)0x400E8238u) /* ENET_RX_ER     ALT1 */",
          "#define IOMUXC_SW_MUX_CTL_PAD_GPIO_LPSR_12     (*(volatile uint32_t *)0x40C08030u) /* GPIO12_IO12 ALT0xA (PHY reset) */",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_32       (*(volatile uint32_t *)0x400E83D0u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_33       (*(volatile uint32_t *)0x400E83D4u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_02  (*(volatile uint32_t *)0x400E8460u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_03  (*(volatile uint32_t *)0x400E8464u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_04  (*(volatile uint32_t *)0x400E8468u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_05  (*(volatile uint32_t *)0x400E846Cu)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_06  (*(volatile uint32_t *)0x400E8470u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_07  (*(volatile uint32_t *)0x400E8474u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_08  (*(volatile uint32_t *)0x400E8478u)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_DISP_B2_09  (*(volatile uint32_t *)0x400E847Cu)",
          "#define IOMUXC_SW_PAD_CTL_PAD_GPIO_LPSR_12     (*(volatile uint32_t *)0x40C08070u)"]
    # --- SNVS RTC (Task: RTC via SNVS). Base 0x40C90000 (cm7 header). Offsets
    #     identical to RT1062; only the base differs. Consumed by rtc.c +
    #     startup.c; LPGPR0/1 used by the rtc_test gate as a warm-reset token. ---
    L += ["", "/* --- SNVS RTC (Secure Non-Volatile Storage: HP RTC + LP secure RTC) --- */",
          "#define SNVS_HPLR      (*(volatile uint32_t *)0x40C90000u)",
          "#define SNVS_HPCOMR    (*(volatile uint32_t *)0x40C90004u)",
          "#define SNVS_HPCR      (*(volatile uint32_t *)0x40C90008u)",
          "#define SNVS_HPSR      (*(volatile uint32_t *)0x40C90014u)",
          "#define SNVS_HPRTCMR   (*(volatile uint32_t *)0x40C90024u)",
          "#define SNVS_HPRTCLR   (*(volatile uint32_t *)0x40C90028u)",
          "#define SNVS_HPTAMR    (*(volatile uint32_t *)0x40C9002Cu)",
          "#define SNVS_HPTALR    (*(volatile uint32_t *)0x40C90030u)",
          "#define SNVS_LPLR      (*(volatile uint32_t *)0x40C90034u)",
          "#define SNVS_LPCR      (*(volatile uint32_t *)0x40C90038u)",
          "#define SNVS_LPSR      (*(volatile uint32_t *)0x40C9004Cu)",
          "#define SNVS_LPSRTCMR  (*(volatile uint32_t *)0x40C90050u)",
          "#define SNVS_LPSRTCLR  (*(volatile uint32_t *)0x40C90054u)",
          "#define SNVS_LPGPR0    (*(volatile uint32_t *)0x40C90100u)",
          "#define SNVS_LPGPR1    (*(volatile uint32_t *)0x40C90104u)",
          "#define SNVS_LPGPR2    (*(volatile uint32_t *)0x40C90108u)",
          "#define SNVS_LPGPR3    (*(volatile uint32_t *)0x40C9010Cu)",
          "",
          "/* SNVS bitfields (RT1176 RM / PERI_SNVS.h) */",
          "#define SNVS_HPCR_RTC_EN     (1u << 0)   /* HP RTC enable            */",
          "#define SNVS_HPCR_HP_TS      (1u << 16)  /* HP time-sync: load HP<-LP */",
          "#define SNVS_LPCR_SRTC_ENV   (1u << 0)   /* LP secure RTC valid/enable */"]
    L += ["", "#endif"]
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")

if __name__ == "__main__": main()
