#include "I2S.h"
/* EVKB SAI1: MCLK=GPIO_AD_17, TX_DATA00=GPIO_AD_21, TX_BCLK=GPIO_AD_22,
 * TX_SYNC=GPIO_AD_23 (all ALT0). Clock root 64 mux=4(AudioPLL) div=16. */
static const I2SClass::hardware_t sai1_hw = {
    SAI1_TCSR, SAI1_TCR1, SAI1_TCR2, SAI1_TCR3, SAI1_TCR4, SAI1_TCR5,
    SAI1_TDR0, SAI1_TFR0, SAI1_TMR,
    CCM_LPCG123_DIRECT, CCM_CLOCK_ROOT64_CONTROL,
    /* clock_root_val */ (4u << 8) | (15u << 0),   // mux 4, div = 16 (val 15)
    IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_17, IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_21,
    IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_22, IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_23,
    IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_17, IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_21,
    IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_22, IOMUXC_SW_PAD_CTL_PAD_GPIO_AD_23,
    IOMUXC_GPR_GPR0,
};
I2SClass I2S(&sai1_hw);
