/* AUTO-GENERATED by tools/gen_imxrt1176_h.py -- do not edit by hand.
 * Standalone Teensy-idiom register defs for NXP i.MX RT1176 (CM7). */
#ifndef _imxrt1176_h_
#define _imxrt1176_h_
#include <stdint.h>

#define ANADIG_OSC_BASE 0x40C84000u
#define ANADIG_PLL_BASE 0x40C84000u
#define CCM_BASE 0x40CC0000u
#define FLEXSPI_BASE 0x400CC000u
#define FLEXSPI2_BASE 0x400D0000u
#define GPIO1_BASE 0x4012C000u
#define GPIO10_BASE 0x40C68000u
#define GPIO11_BASE 0x40C6C000u
#define GPIO12_BASE 0x40C70000u
#define GPIO13_BASE 0x40CA0000u
#define GPIO2_BASE 0x40130000u
#define GPIO3_BASE 0x40134000u
#define GPIO4_BASE 0x40138000u
#define GPIO5_BASE 0x4013C000u
#define GPIO6_BASE 0x40140000u
#define GPIO7_BASE 0x40C5C000u
#define GPIO8_BASE 0x40C60000u
#define GPIO9_BASE 0x40C64000u
#define IOMUXC_BASE 0x400E8000u
#define IOMUXC_GPR_BASE 0x400E4000u
#define GPIO1_DR        (*(volatile uint32_t *)0x4012C000u)
#define GPIO1_GDIR      (*(volatile uint32_t *)0x4012C004u)
#define GPIO1_PSR       (*(volatile uint32_t *)0x4012C008u)
#define GPIO1_DR_SET    (*(volatile uint32_t *)0x4012C084u)
#define GPIO1_DR_CLEAR  (*(volatile uint32_t *)0x4012C088u)
#define GPIO1_DR_TOGGLE (*(volatile uint32_t *)0x4012C08Cu)
#define GPIO2_DR        (*(volatile uint32_t *)0x40130000u)
#define GPIO2_GDIR      (*(volatile uint32_t *)0x40130004u)
#define GPIO2_PSR       (*(volatile uint32_t *)0x40130008u)
#define GPIO2_DR_SET    (*(volatile uint32_t *)0x40130084u)
#define GPIO2_DR_CLEAR  (*(volatile uint32_t *)0x40130088u)
#define GPIO2_DR_TOGGLE (*(volatile uint32_t *)0x4013008Cu)
#define GPIO3_DR        (*(volatile uint32_t *)0x40134000u)
#define GPIO3_GDIR      (*(volatile uint32_t *)0x40134004u)
#define GPIO3_PSR       (*(volatile uint32_t *)0x40134008u)
#define GPIO3_DR_SET    (*(volatile uint32_t *)0x40134084u)
#define GPIO3_DR_CLEAR  (*(volatile uint32_t *)0x40134088u)
#define GPIO3_DR_TOGGLE (*(volatile uint32_t *)0x4013408Cu)
#define GPIO4_DR        (*(volatile uint32_t *)0x40138000u)
#define GPIO4_GDIR      (*(volatile uint32_t *)0x40138004u)
#define GPIO4_PSR       (*(volatile uint32_t *)0x40138008u)
#define GPIO4_DR_SET    (*(volatile uint32_t *)0x40138084u)
#define GPIO4_DR_CLEAR  (*(volatile uint32_t *)0x40138088u)
#define GPIO4_DR_TOGGLE (*(volatile uint32_t *)0x4013808Cu)
#define GPIO5_DR        (*(volatile uint32_t *)0x4013C000u)
#define GPIO5_GDIR      (*(volatile uint32_t *)0x4013C004u)
#define GPIO5_PSR       (*(volatile uint32_t *)0x4013C008u)
#define GPIO5_DR_SET    (*(volatile uint32_t *)0x4013C084u)
#define GPIO5_DR_CLEAR  (*(volatile uint32_t *)0x4013C088u)
#define GPIO5_DR_TOGGLE (*(volatile uint32_t *)0x4013C08Cu)
#define GPIO6_DR        (*(volatile uint32_t *)0x40140000u)
#define GPIO6_GDIR      (*(volatile uint32_t *)0x40140004u)
#define GPIO6_PSR       (*(volatile uint32_t *)0x40140008u)
#define GPIO6_DR_SET    (*(volatile uint32_t *)0x40140084u)
#define GPIO6_DR_CLEAR  (*(volatile uint32_t *)0x40140088u)
#define GPIO6_DR_TOGGLE (*(volatile uint32_t *)0x4014008Cu)
#define GPIO7_DR        (*(volatile uint32_t *)0x40C5C000u)
#define GPIO7_GDIR      (*(volatile uint32_t *)0x40C5C004u)
#define GPIO7_PSR       (*(volatile uint32_t *)0x40C5C008u)
#define GPIO7_DR_SET    (*(volatile uint32_t *)0x40C5C084u)
#define GPIO7_DR_CLEAR  (*(volatile uint32_t *)0x40C5C088u)
#define GPIO7_DR_TOGGLE (*(volatile uint32_t *)0x40C5C08Cu)
#define GPIO8_DR        (*(volatile uint32_t *)0x40C60000u)
#define GPIO8_GDIR      (*(volatile uint32_t *)0x40C60004u)
#define GPIO8_PSR       (*(volatile uint32_t *)0x40C60008u)
#define GPIO8_DR_SET    (*(volatile uint32_t *)0x40C60084u)
#define GPIO8_DR_CLEAR  (*(volatile uint32_t *)0x40C60088u)
#define GPIO8_DR_TOGGLE (*(volatile uint32_t *)0x40C6008Cu)
#define GPIO9_DR        (*(volatile uint32_t *)0x40C64000u)
#define GPIO9_GDIR      (*(volatile uint32_t *)0x40C64004u)
#define GPIO9_PSR       (*(volatile uint32_t *)0x40C64008u)
#define GPIO9_DR_SET    (*(volatile uint32_t *)0x40C64084u)
#define GPIO9_DR_CLEAR  (*(volatile uint32_t *)0x40C64088u)
#define GPIO9_DR_TOGGLE (*(volatile uint32_t *)0x40C6408Cu)
#define GPIO10_DR        (*(volatile uint32_t *)0x40C68000u)
#define GPIO10_GDIR      (*(volatile uint32_t *)0x40C68004u)
#define GPIO10_PSR       (*(volatile uint32_t *)0x40C68008u)
#define GPIO10_DR_SET    (*(volatile uint32_t *)0x40C68084u)
#define GPIO10_DR_CLEAR  (*(volatile uint32_t *)0x40C68088u)
#define GPIO10_DR_TOGGLE (*(volatile uint32_t *)0x40C6808Cu)
#define GPIO11_DR        (*(volatile uint32_t *)0x40C6C000u)
#define GPIO11_GDIR      (*(volatile uint32_t *)0x40C6C004u)
#define GPIO11_PSR       (*(volatile uint32_t *)0x40C6C008u)
#define GPIO11_DR_SET    (*(volatile uint32_t *)0x40C6C084u)
#define GPIO11_DR_CLEAR  (*(volatile uint32_t *)0x40C6C088u)
#define GPIO11_DR_TOGGLE (*(volatile uint32_t *)0x40C6C08Cu)
#define GPIO12_DR        (*(volatile uint32_t *)0x40C70000u)
#define GPIO12_GDIR      (*(volatile uint32_t *)0x40C70004u)
#define GPIO12_PSR       (*(volatile uint32_t *)0x40C70008u)
#define GPIO12_DR_SET    (*(volatile uint32_t *)0x40C70084u)
#define GPIO12_DR_CLEAR  (*(volatile uint32_t *)0x40C70088u)
#define GPIO12_DR_TOGGLE (*(volatile uint32_t *)0x40C7008Cu)
#define GPIO13_DR        (*(volatile uint32_t *)0x40CA0000u)
#define GPIO13_GDIR      (*(volatile uint32_t *)0x40CA0004u)
#define GPIO13_PSR       (*(volatile uint32_t *)0x40CA0008u)
#define GPIO13_DR_SET    (*(volatile uint32_t *)0x40CA0084u)
#define GPIO13_DR_CLEAR  (*(volatile uint32_t *)0x40CA0088u)
#define GPIO13_DR_TOGGLE (*(volatile uint32_t *)0x40CA008Cu)

/* CCM clock roots: CCM->CLOCK_ROOT[n].CONTROL @ CCM_BASE + n*0x80 */
#define CCM_CLOCK_ROOT0_CONTROL (*(volatile uint32_t *)0x40CC0000u) /* M7 */
#define CCM_CLOCK_ROOT2_CONTROL (*(volatile uint32_t *)0x40CC0100u) /* BUS */
#define CCM_CLOCK_ROOT8_CONTROL (*(volatile uint32_t *)0x40CC0400u) /* M7_SYSTICK */
#define CCM_CLOCK_ROOT_CONTROL_MUX(x)  (((uint32_t)(x) << 8) & 0x700u)
#define CCM_CLOCK_ROOT_CONTROL_DIV(x)  (((uint32_t)(x) << 0) & 0x0FFu)

#define ANADIG_PLL_ARM_PLL_CTRL (*(volatile uint32_t *)0x40C84200u)
#define ANADIG_PLL_ARM_PLL_CTRL_DIV_SELECT(x)   (((uint32_t)(x) << 0) & 0x000000FFu)
#define ANADIG_PLL_ARM_PLL_CTRL_HOLD_RING_OFF   (1u << 12)
#define ANADIG_PLL_ARM_PLL_CTRL_POWERUP         (1u << 13)
#define ANADIG_PLL_ARM_PLL_CTRL_ENABLE_CLK      (1u << 14)
#define ANADIG_PLL_ARM_PLL_CTRL_POST_DIV_SEL(x) (((uint32_t)(x) << 15) & 0x00018000u)
#define ANADIG_PLL_ARM_PLL_CTRL_BYPASS          (1u << 17)
#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_STABLE  (1u << 29)
#define ANADIG_PLL_ARM_PLL_CTRL_ARM_PLL_GATE    (1u << 30)
#define ANADIG_OSC_OSC_24M_CTRL (*(volatile uint32_t *)0x40C84020u)
#define ANADIG_OSC_OSC_24M_CTRL_OSC_EN          (1u << 4)
#define ANADIG_OSC_OSC_24M_CTRL_LP_EN           (1u << 2)
#define ANADIG_OSC_OSC_24M_CTRL_OSC_24M_STABLE  (1u << 30)

#define SYST_CSR   (*(volatile uint32_t *)0xE000E010u)
#define SYST_RVR   (*(volatile uint32_t *)0xE000E014u)
#define SYST_CVR   (*(volatile uint32_t *)0xE000E018u)
#define SCB_ICSR   (*(volatile uint32_t *)0xE000ED04u)
#define SCB_ICSR_PENDSTSET (1u << 26)
#define SCB_VTOR   (*(volatile uint32_t *)0xE000ED08u)
#define ARM_DWT_CYCCNT (*(volatile uint32_t *)0xE0001004u)
#define ARM_DWT_CTRL   (*(volatile uint32_t *)0xE0001000u)
#define ARM_DEMCR      (*(volatile uint32_t *)0xE000EDFCu)
#define ARM_DEMCR_TRCENA (1u << 24)

#endif
